/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`viewing_key_decrypt`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ViewingKeyDecryptError {
    Status400(models::GetHealth503Response),
    Status500(models::GetHealth503Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`viewing_key_derive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ViewingKeyDeriveError {
    Status400(models::GetHealth503Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`viewing_key_disclose`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ViewingKeyDiscloseError {
    Status400(models::GetHealth503Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`viewing_key_generate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ViewingKeyGenerateError {
    Status400(models::GetHealth503Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`viewing_key_verify_hierarchy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ViewingKeyVerifyHierarchyError {
    Status400(models::GetHealth503Response),
    UnknownValue(serde_json::Value),
}


pub async fn viewing_key_decrypt(configuration: &configuration::Configuration, viewing_key_decrypt_request: models::ViewingKeyDecryptRequest) -> Result<models::ViewingKeyDecrypt200Response, Error<ViewingKeyDecryptError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_viewing_key_decrypt_request = viewing_key_decrypt_request;

    let uri_str = format!("{}/v1/viewing-key/decrypt", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&p_body_viewing_key_decrypt_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ViewingKeyDecrypt200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ViewingKeyDecrypt200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ViewingKeyDecryptError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Derives a child viewing key from a master key using HMAC-SHA512. Supports hierarchical key trees for scoped compliance access (per-auditor, per-timeframe).
pub async fn viewing_key_derive(configuration: &configuration::Configuration, viewing_key_derive_request: models::ViewingKeyDeriveRequest) -> Result<models::ViewingKeyDerive200Response, Error<ViewingKeyDeriveError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_viewing_key_derive_request = viewing_key_derive_request;

    let uri_str = format!("{}/v1/viewing-key/derive", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&p_body_viewing_key_derive_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ViewingKeyDerive200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ViewingKeyDerive200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ViewingKeyDeriveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Encrypts transaction data so only the viewing key holder can decrypt it (selective compliance).
pub async fn viewing_key_disclose(configuration: &configuration::Configuration, viewing_key_disclose_request: models::ViewingKeyDiscloseRequest) -> Result<models::ViewingKeyDisclose200Response, Error<ViewingKeyDiscloseError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_viewing_key_disclose_request = viewing_key_disclose_request;

    let uri_str = format!("{}/v1/viewing-key/disclose", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&p_body_viewing_key_disclose_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ViewingKeyDisclose200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ViewingKeyDisclose200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ViewingKeyDiscloseError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn viewing_key_generate(configuration: &configuration::Configuration, viewing_key_generate_request: models::ViewingKeyGenerateRequest) -> Result<models::ViewingKeyGenerate200Response, Error<ViewingKeyGenerateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_viewing_key_generate_request = viewing_key_generate_request;

    let uri_str = format!("{}/v1/viewing-key/generate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&p_body_viewing_key_generate_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ViewingKeyGenerate200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ViewingKeyGenerate200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ViewingKeyGenerateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Verifies that a child viewing key was derived from a specific parent key at a given path.
pub async fn viewing_key_verify_hierarchy(configuration: &configuration::Configuration, viewing_key_verify_hierarchy_request: models::ViewingKeyVerifyHierarchyRequest) -> Result<models::ViewingKeyVerifyHierarchy200Response, Error<ViewingKeyVerifyHierarchyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_viewing_key_verify_hierarchy_request = viewing_key_verify_hierarchy_request;

    let uri_str = format!("{}/v1/viewing-key/verify-hierarchy", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-API-Key", value);
    };
    req_builder = req_builder.json(&p_body_viewing_key_verify_hierarchy_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ViewingKeyVerifyHierarchy200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ViewingKeyVerifyHierarchy200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ViewingKeyVerifyHierarchyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

