# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.revoke_admin_key200_response_data import RevokeAdminKey200ResponseData

class TestRevokeAdminKey200ResponseData(unittest.TestCase):
    """RevokeAdminKey200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RevokeAdminKey200ResponseData:
        """Test RevokeAdminKey200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RevokeAdminKey200ResponseData`
        """
        model = RevokeAdminKey200ResponseData()
        if include_optional:
            return RevokeAdminKey200ResponseData(
                revoked = True
            )
        else:
            return RevokeAdminKey200ResponseData(
        )
        """

    def testRevokeAdminKey200ResponseData(self):
        """Test RevokeAdminKey200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
