# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_billing_usage200_response_data import GetBillingUsage200ResponseData

class TestGetBillingUsage200ResponseData(unittest.TestCase):
    """GetBillingUsage200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingUsage200ResponseData:
        """Test GetBillingUsage200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingUsage200ResponseData`
        """
        model = GetBillingUsage200ResponseData()
        if include_optional:
            return GetBillingUsage200ResponseData(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tier = 'free',
                total = 56,
                quota_total = 56,
                categories = {
                    'key' : sipher_client.models.get_billing_usage_200_response_data_categories_value.getBillingUsage_200_response_data_categories_value(
                        count = 56, 
                        quota = 56, )
                    }
            )
        else:
            return GetBillingUsage200ResponseData(
        )
        """

    def testGetBillingUsage200ResponseData(self):
        """Test GetBillingUsage200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
