# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.api.billing_usage_api import BillingUsageApi


class TestBillingUsageApi(unittest.TestCase):
    """BillingUsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingUsageApi()

    def tearDown(self) -> None:
        pass

    def test_create_billing_portal(self) -> None:
        """Test case for create_billing_portal

        Generate customer portal URL
        """
        pass

    def test_create_billing_subscription(self) -> None:
        """Test case for create_billing_subscription

        Create or change subscription
        """
        pass

    def test_get_billing_subscription(self) -> None:
        """Test case for get_billing_subscription

        Get current subscription
        """
        pass

    def test_get_billing_usage(self) -> None:
        """Test case for get_billing_usage

        Get current period usage
        """
        pass

    def test_handle_billing_webhook(self) -> None:
        """Test case for handle_billing_webhook

        Stripe webhook receiver
        """
        pass

    def test_list_billing_invoices(self) -> None:
        """Test case for list_billing_invoices

        List invoices
        """
        pass


if __name__ == '__main__':
    unittest.main()
