# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.delete_session200_response import DeleteSession200Response

class TestDeleteSession200Response(unittest.TestCase):
    """DeleteSession200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteSession200Response:
        """Test DeleteSession200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteSession200Response`
        """
        model = DeleteSession200Response()
        if include_optional:
            return DeleteSession200Response(
                success = True,
                data = sipher_client.models.delete_session_200_response_data.deleteSession_200_response_data(
                    session_id = '', 
                    deleted = True, )
            )
        else:
            return DeleteSession200Response(
        )
        """

    def testDeleteSession200Response(self):
        """Test DeleteSession200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
