/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackendsCompare200ResponseDataRecommendation
 */
export interface BackendsCompare200ResponseDataRecommendation {
    /**
     * 
     * @type {string}
     * @memberof BackendsCompare200ResponseDataRecommendation
     */
    bestOverall?: string;
    /**
     * 
     * @type {string}
     * @memberof BackendsCompare200ResponseDataRecommendation
     */
    bestValue?: string;
    /**
     * 
     * @type {string}
     * @memberof BackendsCompare200ResponseDataRecommendation
     */
    fastest?: string;
    /**
     * 
     * @type {string}
     * @memberof BackendsCompare200ResponseDataRecommendation
     */
    mostPrivate?: string;
    /**
     * 
     * @type {string}
     * @memberof BackendsCompare200ResponseDataRecommendation
     */
    reasoning?: string;
}

/**
 * Check if a given object implements the BackendsCompare200ResponseDataRecommendation interface.
 */
export function instanceOfBackendsCompare200ResponseDataRecommendation(value: object): value is BackendsCompare200ResponseDataRecommendation {
    return true;
}

export function BackendsCompare200ResponseDataRecommendationFromJSON(json: any): BackendsCompare200ResponseDataRecommendation {
    return BackendsCompare200ResponseDataRecommendationFromJSONTyped(json, false);
}

export function BackendsCompare200ResponseDataRecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackendsCompare200ResponseDataRecommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'bestOverall': json['best_overall'] == null ? undefined : json['best_overall'],
        'bestValue': json['best_value'] == null ? undefined : json['best_value'],
        'fastest': json['fastest'] == null ? undefined : json['fastest'],
        'mostPrivate': json['most_private'] == null ? undefined : json['most_private'],
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
    };
}

export function BackendsCompare200ResponseDataRecommendationToJSON(json: any): BackendsCompare200ResponseDataRecommendation {
    return BackendsCompare200ResponseDataRecommendationToJSONTyped(json, false);
}

export function BackendsCompare200ResponseDataRecommendationToJSONTyped(value?: BackendsCompare200ResponseDataRecommendation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'best_overall': value['bestOverall'],
        'best_value': value['bestValue'],
        'fastest': value['fastest'],
        'most_private': value['mostPrivate'],
        'reasoning': value['reasoning'],
    };
}

