/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackendsHealth200ResponseData } from './BackendsHealth200ResponseData';
import {
    BackendsHealth200ResponseDataFromJSON,
    BackendsHealth200ResponseDataFromJSONTyped,
    BackendsHealth200ResponseDataToJSON,
    BackendsHealth200ResponseDataToJSONTyped,
} from './BackendsHealth200ResponseData';

/**
 * 
 * @export
 * @interface BackendsHealth200Response
 */
export interface BackendsHealth200Response {
    /**
     * 
     * @type {boolean}
     * @memberof BackendsHealth200Response
     */
    success?: boolean;
    /**
     * 
     * @type {BackendsHealth200ResponseData}
     * @memberof BackendsHealth200Response
     */
    data?: BackendsHealth200ResponseData;
}

/**
 * Check if a given object implements the BackendsHealth200Response interface.
 */
export function instanceOfBackendsHealth200Response(value: object): value is BackendsHealth200Response {
    return true;
}

export function BackendsHealth200ResponseFromJSON(json: any): BackendsHealth200Response {
    return BackendsHealth200ResponseFromJSONTyped(json, false);
}

export function BackendsHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackendsHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : BackendsHealth200ResponseDataFromJSON(json['data']),
    };
}

export function BackendsHealth200ResponseToJSON(json: any): BackendsHealth200Response {
    return BackendsHealth200ResponseToJSONTyped(json, false);
}

export function BackendsHealth200ResponseToJSONTyped(value?: BackendsHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': BackendsHealth200ResponseDataToJSON(value['data']),
    };
}

