/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackendsSelectRequest
 */
export interface BackendsSelectRequest {
    /**
     * Backend name to prefer
     * @type {string}
     * @memberof BackendsSelectRequest
     */
    backend: string;
}

/**
 * Check if a given object implements the BackendsSelectRequest interface.
 */
export function instanceOfBackendsSelectRequest(value: object): value is BackendsSelectRequest {
    if (!('backend' in value) || value['backend'] === undefined) return false;
    return true;
}

export function BackendsSelectRequestFromJSON(json: any): BackendsSelectRequest {
    return BackendsSelectRequestFromJSONTyped(json, false);
}

export function BackendsSelectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackendsSelectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'backend': json['backend'],
    };
}

export function BackendsSelectRequestToJSON(json: any): BackendsSelectRequest {
    return BackendsSelectRequestToJSONTyped(json, false);
}

export function BackendsSelectRequestToJSONTyped(value?: BackendsSelectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backend': value['backend'],
    };
}

