/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommitmentCreateRequest
 */
export interface CommitmentCreateRequest {
    /**
     * Non-negative integer string
     * @type {string}
     * @memberof CommitmentCreateRequest
     */
    value: string;
    /**
     * Optional custom blinding factor
     * @type {string}
     * @memberof CommitmentCreateRequest
     */
    blindingFactor?: string;
}

/**
 * Check if a given object implements the CommitmentCreateRequest interface.
 */
export function instanceOfCommitmentCreateRequest(value: object): value is CommitmentCreateRequest {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CommitmentCreateRequestFromJSON(json: any): CommitmentCreateRequest {
    return CommitmentCreateRequestFromJSONTyped(json, false);
}

export function CommitmentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitmentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'blindingFactor': json['blindingFactor'] == null ? undefined : json['blindingFactor'],
    };
}

export function CommitmentCreateRequestToJSON(json: any): CommitmentCreateRequest {
    return CommitmentCreateRequestToJSONTyped(json, false);
}

export function CommitmentCreateRequestToJSONTyped(value?: CommitmentCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'blindingFactor': value['blindingFactor'],
    };
}

