/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommitmentAdd200ResponseData
 */
export interface CommitmentAdd200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CommitmentAdd200ResponseData
     */
    commitment?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitmentAdd200ResponseData
     */
    blindingFactor?: string;
}

/**
 * Check if a given object implements the CommitmentAdd200ResponseData interface.
 */
export function instanceOfCommitmentAdd200ResponseData(value: object): value is CommitmentAdd200ResponseData {
    return true;
}

export function CommitmentAdd200ResponseDataFromJSON(json: any): CommitmentAdd200ResponseData {
    return CommitmentAdd200ResponseDataFromJSONTyped(json, false);
}

export function CommitmentAdd200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitmentAdd200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'commitment': json['commitment'] == null ? undefined : json['commitment'],
        'blindingFactor': json['blindingFactor'] == null ? undefined : json['blindingFactor'],
    };
}

export function CommitmentAdd200ResponseDataToJSON(json: any): CommitmentAdd200ResponseData {
    return CommitmentAdd200ResponseDataToJSONTyped(json, false);
}

export function CommitmentAdd200ResponseDataToJSONTyped(value?: CommitmentAdd200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commitment': value['commitment'],
        'blindingFactor': value['blindingFactor'],
    };
}

