/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplianceReport200ResponseDataSummary } from './ComplianceReport200ResponseDataSummary';
import {
    ComplianceReport200ResponseDataSummaryFromJSON,
    ComplianceReport200ResponseDataSummaryFromJSONTyped,
    ComplianceReport200ResponseDataSummaryToJSON,
    ComplianceReport200ResponseDataSummaryToJSONTyped,
} from './ComplianceReport200ResponseDataSummary';

/**
 * 
 * @export
 * @interface ComplianceReport200ResponseData
 */
export interface ComplianceReport200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof ComplianceReport200ResponseData
     */
    reportId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplianceReport200ResponseData
     */
    status?: ComplianceReport200ResponseDataStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ComplianceReport200ResponseData
     */
    generatedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof ComplianceReport200ResponseData
     */
    expiresAt?: number;
    /**
     * 
     * @type {ComplianceReport200ResponseDataSummary}
     * @memberof ComplianceReport200ResponseData
     */
    summary?: ComplianceReport200ResponseDataSummary;
    /**
     * 
     * @type {string}
     * @memberof ComplianceReport200ResponseData
     */
    encryptedReport?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplianceReport200ResponseData
     */
    reportHash?: string;
}


/**
 * @export
 */
export const ComplianceReport200ResponseDataStatusEnum = {
    GENERATED: 'generated',
    ENCRYPTED: 'encrypted'
} as const;
export type ComplianceReport200ResponseDataStatusEnum = typeof ComplianceReport200ResponseDataStatusEnum[keyof typeof ComplianceReport200ResponseDataStatusEnum];


/**
 * Check if a given object implements the ComplianceReport200ResponseData interface.
 */
export function instanceOfComplianceReport200ResponseData(value: object): value is ComplianceReport200ResponseData {
    return true;
}

export function ComplianceReport200ResponseDataFromJSON(json: any): ComplianceReport200ResponseData {
    return ComplianceReport200ResponseDataFromJSONTyped(json, false);
}

export function ComplianceReport200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceReport200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['reportId'] == null ? undefined : json['reportId'],
        'status': json['status'] == null ? undefined : json['status'],
        'generatedAt': json['generatedAt'] == null ? undefined : json['generatedAt'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'summary': json['summary'] == null ? undefined : ComplianceReport200ResponseDataSummaryFromJSON(json['summary']),
        'encryptedReport': json['encryptedReport'] == null ? undefined : json['encryptedReport'],
        'reportHash': json['reportHash'] == null ? undefined : json['reportHash'],
    };
}

export function ComplianceReport200ResponseDataToJSON(json: any): ComplianceReport200ResponseData {
    return ComplianceReport200ResponseDataToJSONTyped(json, false);
}

export function ComplianceReport200ResponseDataToJSONTyped(value?: ComplianceReport200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportId': value['reportId'],
        'status': value['status'],
        'generatedAt': value['generatedAt'],
        'expiresAt': value['expiresAt'],
        'summary': ComplianceReport200ResponseDataSummaryToJSON(value['summary']),
        'encryptedReport': value['encryptedReport'],
        'reportHash': value['reportHash'],
    };
}

