/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComplianceDiscloseRequestAuditorVerification
 */
export interface ComplianceDiscloseRequestAuditorVerification {
    /**
     * 
     * @type {string}
     * @memberof ComplianceDiscloseRequestAuditorVerification
     */
    auditorKeyHash: string;
    /**
     * 
     * @type {string}
     * @memberof ComplianceDiscloseRequestAuditorVerification
     */
    nonce: string;
}

/**
 * Check if a given object implements the ComplianceDiscloseRequestAuditorVerification interface.
 */
export function instanceOfComplianceDiscloseRequestAuditorVerification(value: object): value is ComplianceDiscloseRequestAuditorVerification {
    if (!('auditorKeyHash' in value) || value['auditorKeyHash'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function ComplianceDiscloseRequestAuditorVerificationFromJSON(json: any): ComplianceDiscloseRequestAuditorVerification {
    return ComplianceDiscloseRequestAuditorVerificationFromJSONTyped(json, false);
}

export function ComplianceDiscloseRequestAuditorVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceDiscloseRequestAuditorVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'auditorKeyHash': json['auditorKeyHash'],
        'nonce': json['nonce'],
    };
}

export function ComplianceDiscloseRequestAuditorVerificationToJSON(json: any): ComplianceDiscloseRequestAuditorVerification {
    return ComplianceDiscloseRequestAuditorVerificationToJSONTyped(json, false);
}

export function ComplianceDiscloseRequestAuditorVerificationToJSONTyped(value?: ComplianceDiscloseRequestAuditorVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auditorKeyHash': value['auditorKeyHash'],
        'nonce': value['nonce'],
    };
}

