/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplianceDisclose200ResponseData } from './ComplianceDisclose200ResponseData';
import {
    ComplianceDisclose200ResponseDataFromJSON,
    ComplianceDisclose200ResponseDataFromJSONTyped,
    ComplianceDisclose200ResponseDataToJSON,
    ComplianceDisclose200ResponseDataToJSONTyped,
} from './ComplianceDisclose200ResponseData';

/**
 * 
 * @export
 * @interface ComplianceDisclose200Response
 */
export interface ComplianceDisclose200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceDisclose200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ComplianceDisclose200ResponseData}
     * @memberof ComplianceDisclose200Response
     */
    data?: ComplianceDisclose200ResponseData;
}

/**
 * Check if a given object implements the ComplianceDisclose200Response interface.
 */
export function instanceOfComplianceDisclose200Response(value: object): value is ComplianceDisclose200Response {
    return true;
}

export function ComplianceDisclose200ResponseFromJSON(json: any): ComplianceDisclose200Response {
    return ComplianceDisclose200ResponseFromJSONTyped(json, false);
}

export function ComplianceDisclose200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceDisclose200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ComplianceDisclose200ResponseDataFromJSON(json['data']),
    };
}

export function ComplianceDisclose200ResponseToJSON(json: any): ComplianceDisclose200Response {
    return ComplianceDisclose200ResponseToJSONTyped(json, false);
}

export function ComplianceDisclose200ResponseToJSONTyped(value?: ComplianceDisclose200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ComplianceDisclose200ResponseDataToJSON(value['data']),
    };
}

