/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComputeIncoCiphertexts200ResponseData } from './ComputeIncoCiphertexts200ResponseData';
import {
    ComputeIncoCiphertexts200ResponseDataFromJSON,
    ComputeIncoCiphertexts200ResponseDataFromJSONTyped,
    ComputeIncoCiphertexts200ResponseDataToJSON,
    ComputeIncoCiphertexts200ResponseDataToJSONTyped,
} from './ComputeIncoCiphertexts200ResponseData';

/**
 * 
 * @export
 * @interface ComputeIncoCiphertexts200Response
 */
export interface ComputeIncoCiphertexts200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ComputeIncoCiphertexts200Response
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ComputeIncoCiphertexts200Response
     */
    beta?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200Response
     */
    warning?: string;
    /**
     * 
     * @type {ComputeIncoCiphertexts200ResponseData}
     * @memberof ComputeIncoCiphertexts200Response
     */
    data?: ComputeIncoCiphertexts200ResponseData;
}

/**
 * Check if a given object implements the ComputeIncoCiphertexts200Response interface.
 */
export function instanceOfComputeIncoCiphertexts200Response(value: object): value is ComputeIncoCiphertexts200Response {
    return true;
}

export function ComputeIncoCiphertexts200ResponseFromJSON(json: any): ComputeIncoCiphertexts200Response {
    return ComputeIncoCiphertexts200ResponseFromJSONTyped(json, false);
}

export function ComputeIncoCiphertexts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComputeIncoCiphertexts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'beta': json['beta'] == null ? undefined : json['beta'],
        'warning': json['warning'] == null ? undefined : json['warning'],
        'data': json['data'] == null ? undefined : ComputeIncoCiphertexts200ResponseDataFromJSON(json['data']),
    };
}

export function ComputeIncoCiphertexts200ResponseToJSON(json: any): ComputeIncoCiphertexts200Response {
    return ComputeIncoCiphertexts200ResponseToJSONTyped(json, false);
}

export function ComputeIncoCiphertexts200ResponseToJSONTyped(value?: ComputeIncoCiphertexts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'beta': value['beta'],
        'warning': value['warning'],
        'data': ComputeIncoCiphertexts200ResponseDataToJSON(value['data']),
    };
}

