/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComputeIncoCiphertexts200ResponseData
 */
export interface ComputeIncoCiphertexts200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    computationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    operation?: string;
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    scheme?: string;
    /**
     * 
     * @type {number}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    operandCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    resultCiphertext?: string;
    /**
     * 
     * @type {number}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    noiseBudgetRemaining?: number;
    /**
     * 
     * @type {string}
     * @memberof ComputeIncoCiphertexts200ResponseData
     */
    status?: ComputeIncoCiphertexts200ResponseDataStatusEnum;
}


/**
 * @export
 */
export const ComputeIncoCiphertexts200ResponseDataStatusEnum = {
    COMPLETED: 'completed'
} as const;
export type ComputeIncoCiphertexts200ResponseDataStatusEnum = typeof ComputeIncoCiphertexts200ResponseDataStatusEnum[keyof typeof ComputeIncoCiphertexts200ResponseDataStatusEnum];


/**
 * Check if a given object implements the ComputeIncoCiphertexts200ResponseData interface.
 */
export function instanceOfComputeIncoCiphertexts200ResponseData(value: object): value is ComputeIncoCiphertexts200ResponseData {
    return true;
}

export function ComputeIncoCiphertexts200ResponseDataFromJSON(json: any): ComputeIncoCiphertexts200ResponseData {
    return ComputeIncoCiphertexts200ResponseDataFromJSONTyped(json, false);
}

export function ComputeIncoCiphertexts200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComputeIncoCiphertexts200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'computationId': json['computationId'] == null ? undefined : json['computationId'],
        'operation': json['operation'] == null ? undefined : json['operation'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'operandCount': json['operandCount'] == null ? undefined : json['operandCount'],
        'resultCiphertext': json['resultCiphertext'] == null ? undefined : json['resultCiphertext'],
        'noiseBudgetRemaining': json['noiseBudgetRemaining'] == null ? undefined : json['noiseBudgetRemaining'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ComputeIncoCiphertexts200ResponseDataToJSON(json: any): ComputeIncoCiphertexts200ResponseData {
    return ComputeIncoCiphertexts200ResponseDataToJSONTyped(json, false);
}

export function ComputeIncoCiphertexts200ResponseDataToJSONTyped(value?: ComputeIncoCiphertexts200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computationId': value['computationId'],
        'operation': value['operation'],
        'scheme': value['scheme'],
        'operandCount': value['operandCount'],
        'resultCiphertext': value['resultCiphertext'],
        'noiseBudgetRemaining': value['noiseBudgetRemaining'],
        'status': value['status'],
    };
}

