/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSessionRequestDefaults } from './CreateSessionRequestDefaults';
import {
    CreateSessionRequestDefaultsFromJSON,
    CreateSessionRequestDefaultsFromJSONTyped,
    CreateSessionRequestDefaultsToJSON,
    CreateSessionRequestDefaultsToJSONTyped,
} from './CreateSessionRequestDefaults';

/**
 * 
 * @export
 * @interface CreateSessionRequest
 */
export interface CreateSessionRequest {
    /**
     * 
     * @type {CreateSessionRequestDefaults}
     * @memberof CreateSessionRequest
     */
    defaults: CreateSessionRequestDefaults;
    /**
     * Session TTL in seconds (default: 3600, max: 86400)
     * @type {number}
     * @memberof CreateSessionRequest
     */
    ttlSeconds?: number;
}

/**
 * Check if a given object implements the CreateSessionRequest interface.
 */
export function instanceOfCreateSessionRequest(value: object): value is CreateSessionRequest {
    if (!('defaults' in value) || value['defaults'] === undefined) return false;
    return true;
}

export function CreateSessionRequestFromJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestFromJSONTyped(json, false);
}

export function CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaults': CreateSessionRequestDefaultsFromJSON(json['defaults']),
        'ttlSeconds': json['ttlSeconds'] == null ? undefined : json['ttlSeconds'],
    };
}

export function CreateSessionRequestToJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestToJSONTyped(json, false);
}

export function CreateSessionRequestToJSONTyped(value?: CreateSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaults': CreateSessionRequestDefaultsToJSON(value['defaults']),
        'ttlSeconds': value['ttlSeconds'],
    };
}

