/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBillingPortal200ResponseData } from './CreateBillingPortal200ResponseData';
import {
    CreateBillingPortal200ResponseDataFromJSON,
    CreateBillingPortal200ResponseDataFromJSONTyped,
    CreateBillingPortal200ResponseDataToJSON,
    CreateBillingPortal200ResponseDataToJSONTyped,
} from './CreateBillingPortal200ResponseData';

/**
 * 
 * @export
 * @interface CreateBillingPortal200Response
 */
export interface CreateBillingPortal200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateBillingPortal200Response
     */
    success?: boolean;
    /**
     * 
     * @type {CreateBillingPortal200ResponseData}
     * @memberof CreateBillingPortal200Response
     */
    data?: CreateBillingPortal200ResponseData;
}

/**
 * Check if a given object implements the CreateBillingPortal200Response interface.
 */
export function instanceOfCreateBillingPortal200Response(value: object): value is CreateBillingPortal200Response {
    return true;
}

export function CreateBillingPortal200ResponseFromJSON(json: any): CreateBillingPortal200Response {
    return CreateBillingPortal200ResponseFromJSONTyped(json, false);
}

export function CreateBillingPortal200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBillingPortal200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : CreateBillingPortal200ResponseDataFromJSON(json['data']),
    };
}

export function CreateBillingPortal200ResponseToJSON(json: any): CreateBillingPortal200Response {
    return CreateBillingPortal200ResponseToJSONTyped(json, false);
}

export function CreateBillingPortal200ResponseToJSONTyped(value?: CreateBillingPortal200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateBillingPortal200ResponseDataToJSON(value['data']),
    };
}

