/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSession201ResponseData } from './CreateSession201ResponseData';
import {
    CreateSession201ResponseDataFromJSON,
    CreateSession201ResponseDataFromJSONTyped,
    CreateSession201ResponseDataToJSON,
    CreateSession201ResponseDataToJSONTyped,
} from './CreateSession201ResponseData';

/**
 * 
 * @export
 * @interface CreateSession201Response
 */
export interface CreateSession201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateSession201Response
     */
    success?: boolean;
    /**
     * 
     * @type {CreateSession201ResponseData}
     * @memberof CreateSession201Response
     */
    data?: CreateSession201ResponseData;
}

/**
 * Check if a given object implements the CreateSession201Response interface.
 */
export function instanceOfCreateSession201Response(value: object): value is CreateSession201Response {
    return true;
}

export function CreateSession201ResponseFromJSON(json: any): CreateSession201Response {
    return CreateSession201ResponseFromJSONTyped(json, false);
}

export function CreateSession201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSession201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : CreateSession201ResponseDataFromJSON(json['data']),
    };
}

export function CreateSession201ResponseToJSON(json: any): CreateSession201Response {
    return CreateSession201ResponseToJSONTyped(json, false);
}

export function CreateSession201ResponseToJSONTyped(value?: CreateSession201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateSession201ResponseDataToJSON(value['data']),
    };
}

