/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdminKey201ResponseData
 */
export interface CreateAdminKey201ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateAdminKey201ResponseData
     */
    id?: string;
    /**
     * Raw API key — shown only once
     * @type {string}
     * @memberof CreateAdminKey201ResponseData
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminKey201ResponseData
     */
    tier?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminKey201ResponseData
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateAdminKey201ResponseData
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateAdminKey201ResponseData
     */
    expiresAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof CreateAdminKey201ResponseData
     */
    limits?: object;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminKey201ResponseData
     */
    notice?: string;
}

/**
 * Check if a given object implements the CreateAdminKey201ResponseData interface.
 */
export function instanceOfCreateAdminKey201ResponseData(value: object): value is CreateAdminKey201ResponseData {
    return true;
}

export function CreateAdminKey201ResponseDataFromJSON(json: any): CreateAdminKey201ResponseData {
    return CreateAdminKey201ResponseDataFromJSONTyped(json, false);
}

export function CreateAdminKey201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdminKey201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'tier': json['tier'] == null ? undefined : json['tier'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'limits': json['limits'] == null ? undefined : json['limits'],
        'notice': json['notice'] == null ? undefined : json['notice'],
    };
}

export function CreateAdminKey201ResponseDataToJSON(json: any): CreateAdminKey201ResponseData {
    return CreateAdminKey201ResponseDataToJSONTyped(json, false);
}

export function CreateAdminKey201ResponseDataToJSONTyped(value?: CreateAdminKey201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'tier': value['tier'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'limits': value['limits'],
        'notice': value['notice'],
    };
}

