/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CsplUnwrap200ResponseData
 */
export interface CsplUnwrap200ResponseData {
    /**
     * Transaction signature
     * @type {string}
     * @memberof CsplUnwrap200ResponseData
     */
    signature?: string;
    /**
     * Decrypted amount as string
     * @type {string}
     * @memberof CsplUnwrap200ResponseData
     */
    amount?: string;
}

/**
 * Check if a given object implements the CsplUnwrap200ResponseData interface.
 */
export function instanceOfCsplUnwrap200ResponseData(value: object): value is CsplUnwrap200ResponseData {
    return true;
}

export function CsplUnwrap200ResponseDataFromJSON(json: any): CsplUnwrap200ResponseData {
    return CsplUnwrap200ResponseDataFromJSONTyped(json, false);
}

export function CsplUnwrap200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsplUnwrap200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'signature': json['signature'] == null ? undefined : json['signature'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function CsplUnwrap200ResponseDataToJSON(json: any): CsplUnwrap200ResponseData {
    return CsplUnwrap200ResponseDataToJSONTyped(json, false);
}

export function CsplUnwrap200ResponseDataToJSONTyped(value?: CsplUnwrap200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signature': value['signature'],
        'amount': value['amount'],
    };
}

