/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CsplTransferRequest
 */
export interface CsplTransferRequest {
    /**
     * C-SPL token mint identifier
     * @type {string}
     * @memberof CsplTransferRequest
     */
    csplMint: string;
    /**
     * Base58-encoded Solana public key
     * @type {string}
     * @memberof CsplTransferRequest
     */
    from: string;
    /**
     * Base58-encoded Solana public key
     * @type {string}
     * @memberof CsplTransferRequest
     */
    to: string;
    /**
     * Encrypted transfer amount as hex
     * @type {string}
     * @memberof CsplTransferRequest
     */
    encryptedAmount: string;
    /**
     * Optional memo
     * @type {string}
     * @memberof CsplTransferRequest
     */
    memo?: string;
}

/**
 * Check if a given object implements the CsplTransferRequest interface.
 */
export function instanceOfCsplTransferRequest(value: object): value is CsplTransferRequest {
    if (!('csplMint' in value) || value['csplMint'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('encryptedAmount' in value) || value['encryptedAmount'] === undefined) return false;
    return true;
}

export function CsplTransferRequestFromJSON(json: any): CsplTransferRequest {
    return CsplTransferRequestFromJSONTyped(json, false);
}

export function CsplTransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsplTransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'csplMint': json['csplMint'],
        'from': json['from'],
        'to': json['to'],
        'encryptedAmount': json['encryptedAmount'],
        'memo': json['memo'] == null ? undefined : json['memo'],
    };
}

export function CsplTransferRequestToJSON(json: any): CsplTransferRequest {
    return CsplTransferRequestToJSONTyped(json, false);
}

export function CsplTransferRequestToJSONTyped(value?: CsplTransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csplMint': value['csplMint'],
        'from': value['from'],
        'to': value['to'],
        'encryptedAmount': value['encryptedAmount'],
        'memo': value['memo'],
    };
}

