/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecryptIncoResultRequest
 */
export interface DecryptIncoResultRequest {
    /**
     * Computation ID to decrypt
     * @type {string}
     * @memberof DecryptIncoResultRequest
     */
    computationId: string;
}

/**
 * Check if a given object implements the DecryptIncoResultRequest interface.
 */
export function instanceOfDecryptIncoResultRequest(value: object): value is DecryptIncoResultRequest {
    if (!('computationId' in value) || value['computationId'] === undefined) return false;
    return true;
}

export function DecryptIncoResultRequestFromJSON(json: any): DecryptIncoResultRequest {
    return DecryptIncoResultRequestFromJSONTyped(json, false);
}

export function DecryptIncoResultRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptIncoResultRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'computationId': json['computationId'],
    };
}

export function DecryptIncoResultRequestToJSON(json: any): DecryptIncoResultRequest {
    return DecryptIncoResultRequestToJSONTyped(json, false);
}

export function DecryptIncoResultRequestToJSONTyped(value?: DecryptIncoResultRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computationId': value['computationId'],
    };
}

