/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecryptIncoResult200ResponseData
 */
export interface DecryptIncoResult200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof DecryptIncoResult200ResponseData
     */
    computationId?: string;
    /**
     * 
     * @type {string}
     * @memberof DecryptIncoResult200ResponseData
     */
    operation?: string;
    /**
     * 
     * @type {string}
     * @memberof DecryptIncoResult200ResponseData
     */
    decryptedOutput?: string;
    /**
     * 
     * @type {string}
     * @memberof DecryptIncoResult200ResponseData
     */
    verificationHash?: string;
}

/**
 * Check if a given object implements the DecryptIncoResult200ResponseData interface.
 */
export function instanceOfDecryptIncoResult200ResponseData(value: object): value is DecryptIncoResult200ResponseData {
    return true;
}

export function DecryptIncoResult200ResponseDataFromJSON(json: any): DecryptIncoResult200ResponseData {
    return DecryptIncoResult200ResponseDataFromJSONTyped(json, false);
}

export function DecryptIncoResult200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptIncoResult200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'computationId': json['computationId'] == null ? undefined : json['computationId'],
        'operation': json['operation'] == null ? undefined : json['operation'],
        'decryptedOutput': json['decryptedOutput'] == null ? undefined : json['decryptedOutput'],
        'verificationHash': json['verificationHash'] == null ? undefined : json['verificationHash'],
    };
}

export function DecryptIncoResult200ResponseDataToJSON(json: any): DecryptIncoResult200ResponseData {
    return DecryptIncoResult200ResponseDataToJSONTyped(json, false);
}

export function DecryptIncoResult200ResponseDataToJSONTyped(value?: DecryptIncoResult200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computationId': value['computationId'],
        'operation': value['operation'],
        'decryptedOutput': value['decryptedOutput'],
        'verificationHash': value['verificationHash'],
    };
}

