/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecryptArciumResultRequestViewingKey } from './DecryptArciumResultRequestViewingKey';
import {
    DecryptArciumResultRequestViewingKeyFromJSON,
    DecryptArciumResultRequestViewingKeyFromJSONTyped,
    DecryptArciumResultRequestViewingKeyToJSON,
    DecryptArciumResultRequestViewingKeyToJSONTyped,
} from './DecryptArciumResultRequestViewingKey';

/**
 * 
 * @export
 * @interface DecryptArciumResultRequest
 */
export interface DecryptArciumResultRequest {
    /**
     * 
     * @type {string}
     * @memberof DecryptArciumResultRequest
     */
    computationId: string;
    /**
     * 
     * @type {DecryptArciumResultRequestViewingKey}
     * @memberof DecryptArciumResultRequest
     */
    viewingKey: DecryptArciumResultRequestViewingKey;
}

/**
 * Check if a given object implements the DecryptArciumResultRequest interface.
 */
export function instanceOfDecryptArciumResultRequest(value: object): value is DecryptArciumResultRequest {
    if (!('computationId' in value) || value['computationId'] === undefined) return false;
    if (!('viewingKey' in value) || value['viewingKey'] === undefined) return false;
    return true;
}

export function DecryptArciumResultRequestFromJSON(json: any): DecryptArciumResultRequest {
    return DecryptArciumResultRequestFromJSONTyped(json, false);
}

export function DecryptArciumResultRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptArciumResultRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'computationId': json['computationId'],
        'viewingKey': DecryptArciumResultRequestViewingKeyFromJSON(json['viewingKey']),
    };
}

export function DecryptArciumResultRequestToJSON(json: any): DecryptArciumResultRequest {
    return DecryptArciumResultRequestToJSONTyped(json, false);
}

export function DecryptArciumResultRequestToJSONTyped(value?: DecryptArciumResultRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computationId': value['computationId'],
        'viewingKey': DecryptArciumResultRequestViewingKeyToJSON(value['viewingKey']),
    };
}

