/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecryptArciumResult200ResponseData } from './DecryptArciumResult200ResponseData';
import {
    DecryptArciumResult200ResponseDataFromJSON,
    DecryptArciumResult200ResponseDataFromJSONTyped,
    DecryptArciumResult200ResponseDataToJSON,
    DecryptArciumResult200ResponseDataToJSONTyped,
} from './DecryptArciumResult200ResponseData';

/**
 * 
 * @export
 * @interface DecryptArciumResult200Response
 */
export interface DecryptArciumResult200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DecryptArciumResult200Response
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DecryptArciumResult200Response
     */
    beta?: boolean;
    /**
     * 
     * @type {DecryptArciumResult200ResponseData}
     * @memberof DecryptArciumResult200Response
     */
    data?: DecryptArciumResult200ResponseData;
}

/**
 * Check if a given object implements the DecryptArciumResult200Response interface.
 */
export function instanceOfDecryptArciumResult200Response(value: object): value is DecryptArciumResult200Response {
    return true;
}

export function DecryptArciumResult200ResponseFromJSON(json: any): DecryptArciumResult200Response {
    return DecryptArciumResult200ResponseFromJSONTyped(json, false);
}

export function DecryptArciumResult200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptArciumResult200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'beta': json['beta'] == null ? undefined : json['beta'],
        'data': json['data'] == null ? undefined : DecryptArciumResult200ResponseDataFromJSON(json['data']),
    };
}

export function DecryptArciumResult200ResponseToJSON(json: any): DecryptArciumResult200Response {
    return DecryptArciumResult200ResponseToJSONTyped(json, false);
}

export function DecryptArciumResult200ResponseToJSONTyped(value?: DecryptArciumResult200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'beta': value['beta'],
        'data': DecryptArciumResult200ResponseDataToJSON(value['data']),
    };
}

