/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetHealth503ResponseError } from './GetHealth503ResponseError';
import {
    GetHealth503ResponseErrorFromJSON,
    GetHealth503ResponseErrorFromJSONTyped,
    GetHealth503ResponseErrorToJSON,
    GetHealth503ResponseErrorToJSONTyped,
} from './GetHealth503ResponseError';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponse
     */
    success: ErrorResponseSuccessEnum;
    /**
     * 
     * @type {GetHealth503ResponseError}
     * @memberof ErrorResponse
     */
    error: GetHealth503ResponseError;
}


/**
 * @export
 */
export const ErrorResponseSuccessEnum = {
    FALSE: false
} as const;
export type ErrorResponseSuccessEnum = typeof ErrorResponseSuccessEnum[keyof typeof ErrorResponseSuccessEnum];


/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': GetHealth503ResponseErrorFromJSON(json['error']),
    };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
    return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(value?: ErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': GetHealth503ResponseErrorToJSON(value['error']),
    };
}

