/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmTransferData
 */
export interface EvmTransferData {
    /**
     * 
     * @type {string}
     * @memberof EvmTransferData
     */
    type: EvmTransferDataTypeEnum;
    /**
     * Recipient or token contract address
     * @type {string}
     * @memberof EvmTransferData
     */
    to: string;
    /**
     * Native currency amount (wei)
     * @type {string}
     * @memberof EvmTransferData
     */
    value: string;
    /**
     * Calldata (0x for native, ABI-encoded for ERC20)
     * @type {string}
     * @memberof EvmTransferData
     */
    data: string;
    /**
     * 
     * @type {number}
     * @memberof EvmTransferData
     */
    chainId: number;
    /**
     * 
     * @type {string}
     * @memberof EvmTransferData
     */
    tokenContract?: string;
}


/**
 * @export
 */
export const EvmTransferDataTypeEnum = {
    EVM: 'evm'
} as const;
export type EvmTransferDataTypeEnum = typeof EvmTransferDataTypeEnum[keyof typeof EvmTransferDataTypeEnum];


/**
 * Check if a given object implements the EvmTransferData interface.
 */
export function instanceOfEvmTransferData(value: object): value is EvmTransferData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    return true;
}

export function EvmTransferDataFromJSON(json: any): EvmTransferData {
    return EvmTransferDataFromJSONTyped(json, false);
}

export function EvmTransferDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmTransferData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'to': json['to'],
        'value': json['value'],
        'data': json['data'],
        'chainId': json['chainId'],
        'tokenContract': json['tokenContract'] == null ? undefined : json['tokenContract'],
    };
}

export function EvmTransferDataToJSON(json: any): EvmTransferData {
    return EvmTransferDataToJSONTyped(json, false);
}

export function EvmTransferDataToJSONTyped(value?: EvmTransferData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'to': value['to'],
        'value': value['value'],
        'data': value['data'],
        'chainId': value['chainId'],
        'tokenContract': value['tokenContract'],
    };
}

