/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetArciumComputationStatus200ResponseData } from './GetArciumComputationStatus200ResponseData';
import {
    GetArciumComputationStatus200ResponseDataFromJSON,
    GetArciumComputationStatus200ResponseDataFromJSONTyped,
    GetArciumComputationStatus200ResponseDataToJSON,
    GetArciumComputationStatus200ResponseDataToJSONTyped,
} from './GetArciumComputationStatus200ResponseData';

/**
 * 
 * @export
 * @interface GetArciumComputationStatus200Response
 */
export interface GetArciumComputationStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetArciumComputationStatus200Response
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetArciumComputationStatus200Response
     */
    beta?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetArciumComputationStatus200Response
     */
    warning?: string;
    /**
     * 
     * @type {GetArciumComputationStatus200ResponseData}
     * @memberof GetArciumComputationStatus200Response
     */
    data?: GetArciumComputationStatus200ResponseData;
}

/**
 * Check if a given object implements the GetArciumComputationStatus200Response interface.
 */
export function instanceOfGetArciumComputationStatus200Response(value: object): value is GetArciumComputationStatus200Response {
    return true;
}

export function GetArciumComputationStatus200ResponseFromJSON(json: any): GetArciumComputationStatus200Response {
    return GetArciumComputationStatus200ResponseFromJSONTyped(json, false);
}

export function GetArciumComputationStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArciumComputationStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'beta': json['beta'] == null ? undefined : json['beta'],
        'warning': json['warning'] == null ? undefined : json['warning'],
        'data': json['data'] == null ? undefined : GetArciumComputationStatus200ResponseDataFromJSON(json['data']),
    };
}

export function GetArciumComputationStatus200ResponseToJSON(json: any): GetArciumComputationStatus200Response {
    return GetArciumComputationStatus200ResponseToJSONTyped(json, false);
}

export function GetArciumComputationStatus200ResponseToJSONTyped(value?: GetArciumComputationStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'beta': value['beta'],
        'warning': value['warning'],
        'data': GetArciumComputationStatus200ResponseDataToJSON(value['data']),
    };
}

