/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetComplianceReport200ResponseData
 */
export interface GetComplianceReport200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetComplianceReport200ResponseData
     */
    reportId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetComplianceReport200ResponseData
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof GetComplianceReport200ResponseData
     */
    generatedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof GetComplianceReport200ResponseData
     */
    expiresAt?: number;
    /**
     * 
     * @type {object}
     * @memberof GetComplianceReport200ResponseData
     */
    summary?: object;
    /**
     * 
     * @type {string}
     * @memberof GetComplianceReport200ResponseData
     */
    encryptedReport?: string;
    /**
     * 
     * @type {string}
     * @memberof GetComplianceReport200ResponseData
     */
    reportHash?: string;
}

/**
 * Check if a given object implements the GetComplianceReport200ResponseData interface.
 */
export function instanceOfGetComplianceReport200ResponseData(value: object): value is GetComplianceReport200ResponseData {
    return true;
}

export function GetComplianceReport200ResponseDataFromJSON(json: any): GetComplianceReport200ResponseData {
    return GetComplianceReport200ResponseDataFromJSONTyped(json, false);
}

export function GetComplianceReport200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetComplianceReport200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['reportId'] == null ? undefined : json['reportId'],
        'status': json['status'] == null ? undefined : json['status'],
        'generatedAt': json['generatedAt'] == null ? undefined : json['generatedAt'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'encryptedReport': json['encryptedReport'] == null ? undefined : json['encryptedReport'],
        'reportHash': json['reportHash'] == null ? undefined : json['reportHash'],
    };
}

export function GetComplianceReport200ResponseDataToJSON(json: any): GetComplianceReport200ResponseData {
    return GetComplianceReport200ResponseDataToJSONTyped(json, false);
}

export function GetComplianceReport200ResponseDataToJSONTyped(value?: GetComplianceReport200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportId': value['reportId'],
        'status': value['status'],
        'generatedAt': value['generatedAt'],
        'expiresAt': value['expiresAt'],
        'summary': value['summary'],
        'encryptedReport': value['encryptedReport'],
        'reportHash': value['reportHash'],
    };
}

