/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetJitoBundleStatus200ResponseData } from './GetJitoBundleStatus200ResponseData';
import {
    GetJitoBundleStatus200ResponseDataFromJSON,
    GetJitoBundleStatus200ResponseDataFromJSONTyped,
    GetJitoBundleStatus200ResponseDataToJSON,
    GetJitoBundleStatus200ResponseDataToJSONTyped,
} from './GetJitoBundleStatus200ResponseData';

/**
 * 
 * @export
 * @interface GetJitoBundleStatus200Response
 */
export interface GetJitoBundleStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetJitoBundleStatus200Response
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetJitoBundleStatus200Response
     */
    beta?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetJitoBundleStatus200Response
     */
    warning?: string;
    /**
     * 
     * @type {GetJitoBundleStatus200ResponseData}
     * @memberof GetJitoBundleStatus200Response
     */
    data?: GetJitoBundleStatus200ResponseData;
}

/**
 * Check if a given object implements the GetJitoBundleStatus200Response interface.
 */
export function instanceOfGetJitoBundleStatus200Response(value: object): value is GetJitoBundleStatus200Response {
    return true;
}

export function GetJitoBundleStatus200ResponseFromJSON(json: any): GetJitoBundleStatus200Response {
    return GetJitoBundleStatus200ResponseFromJSONTyped(json, false);
}

export function GetJitoBundleStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJitoBundleStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'beta': json['beta'] == null ? undefined : json['beta'],
        'warning': json['warning'] == null ? undefined : json['warning'],
        'data': json['data'] == null ? undefined : GetJitoBundleStatus200ResponseDataFromJSON(json['data']),
    };
}

export function GetJitoBundleStatus200ResponseToJSON(json: any): GetJitoBundleStatus200Response {
    return GetJitoBundleStatus200ResponseToJSONTyped(json, false);
}

export function GetJitoBundleStatus200ResponseToJSONTyped(value?: GetJitoBundleStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'beta': value['beta'],
        'warning': value['warning'],
        'data': GetJitoBundleStatus200ResponseDataToJSON(value['data']),
    };
}

