/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRpcProviders200ResponseDataSupportedInner
 */
export interface GetRpcProviders200ResponseDataSupportedInner {
    /**
     * 
     * @type {string}
     * @memberof GetRpcProviders200ResponseDataSupportedInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRpcProviders200ResponseDataSupportedInner
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetRpcProviders200ResponseDataSupportedInner
     */
    config?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetRpcProviders200ResponseDataSupportedInner
     */
    url?: string;
}

/**
 * Check if a given object implements the GetRpcProviders200ResponseDataSupportedInner interface.
 */
export function instanceOfGetRpcProviders200ResponseDataSupportedInner(value: object): value is GetRpcProviders200ResponseDataSupportedInner {
    return true;
}

export function GetRpcProviders200ResponseDataSupportedInnerFromJSON(json: any): GetRpcProviders200ResponseDataSupportedInner {
    return GetRpcProviders200ResponseDataSupportedInnerFromJSONTyped(json, false);
}

export function GetRpcProviders200ResponseDataSupportedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRpcProviders200ResponseDataSupportedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'config': json['config'] == null ? undefined : json['config'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GetRpcProviders200ResponseDataSupportedInnerToJSON(json: any): GetRpcProviders200ResponseDataSupportedInner {
    return GetRpcProviders200ResponseDataSupportedInnerToJSONTyped(json, false);
}

export function GetRpcProviders200ResponseDataSupportedInnerToJSONTyped(value?: GetRpcProviders200ResponseDataSupportedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'config': value['config'],
        'url': value['url'],
    };
}

