/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRpcProviders200ResponseData } from './GetRpcProviders200ResponseData';
import {
    GetRpcProviders200ResponseDataFromJSON,
    GetRpcProviders200ResponseDataFromJSONTyped,
    GetRpcProviders200ResponseDataToJSON,
    GetRpcProviders200ResponseDataToJSONTyped,
} from './GetRpcProviders200ResponseData';

/**
 * 
 * @export
 * @interface GetRpcProviders200Response
 */
export interface GetRpcProviders200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetRpcProviders200Response
     */
    success?: GetRpcProviders200ResponseSuccessEnum;
    /**
     * 
     * @type {GetRpcProviders200ResponseData}
     * @memberof GetRpcProviders200Response
     */
    data?: GetRpcProviders200ResponseData;
}


/**
 * @export
 */
export const GetRpcProviders200ResponseSuccessEnum = {
    TRUE: true
} as const;
export type GetRpcProviders200ResponseSuccessEnum = typeof GetRpcProviders200ResponseSuccessEnum[keyof typeof GetRpcProviders200ResponseSuccessEnum];


/**
 * Check if a given object implements the GetRpcProviders200Response interface.
 */
export function instanceOfGetRpcProviders200Response(value: object): value is GetRpcProviders200Response {
    return true;
}

export function GetRpcProviders200ResponseFromJSON(json: any): GetRpcProviders200Response {
    return GetRpcProviders200ResponseFromJSONTyped(json, false);
}

export function GetRpcProviders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRpcProviders200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : GetRpcProviders200ResponseDataFromJSON(json['data']),
    };
}

export function GetRpcProviders200ResponseToJSON(json: any): GetRpcProviders200Response {
    return GetRpcProviders200ResponseToJSONTyped(json, false);
}

export function GetRpcProviders200ResponseToJSONTyped(value?: GetRpcProviders200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetRpcProviders200ResponseDataToJSON(value['data']),
    };
}

