/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBillingInvoices200ResponseData
 */
export interface ListBillingInvoices200ResponseData {
    /**
     * 
     * @type {Array<any>}
     * @memberof ListBillingInvoices200ResponseData
     */
    invoices?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof ListBillingInvoices200ResponseData
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ListBillingInvoices200ResponseData
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListBillingInvoices200ResponseData
     */
    offset?: number;
}

/**
 * Check if a given object implements the ListBillingInvoices200ResponseData interface.
 */
export function instanceOfListBillingInvoices200ResponseData(value: object): value is ListBillingInvoices200ResponseData {
    return true;
}

export function ListBillingInvoices200ResponseDataFromJSON(json: any): ListBillingInvoices200ResponseData {
    return ListBillingInvoices200ResponseDataFromJSONTyped(json, false);
}

export function ListBillingInvoices200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBillingInvoices200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'invoices': json['invoices'] == null ? undefined : json['invoices'],
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function ListBillingInvoices200ResponseDataToJSON(json: any): ListBillingInvoices200ResponseData {
    return ListBillingInvoices200ResponseDataToJSONTyped(json, false);
}

export function ListBillingInvoices200ResponseDataToJSONTyped(value?: ListBillingInvoices200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoices': value['invoices'],
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

