/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAdminKeys200ResponseData } from './ListAdminKeys200ResponseData';
import {
    ListAdminKeys200ResponseDataFromJSON,
    ListAdminKeys200ResponseDataFromJSONTyped,
    ListAdminKeys200ResponseDataToJSON,
    ListAdminKeys200ResponseDataToJSONTyped,
} from './ListAdminKeys200ResponseData';

/**
 * 
 * @export
 * @interface ListAdminKeys200Response
 */
export interface ListAdminKeys200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListAdminKeys200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ListAdminKeys200ResponseData}
     * @memberof ListAdminKeys200Response
     */
    data?: ListAdminKeys200ResponseData;
}

/**
 * Check if a given object implements the ListAdminKeys200Response interface.
 */
export function instanceOfListAdminKeys200Response(value: object): value is ListAdminKeys200Response {
    return true;
}

export function ListAdminKeys200ResponseFromJSON(json: any): ListAdminKeys200Response {
    return ListAdminKeys200ResponseFromJSONTyped(json, false);
}

export function ListAdminKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAdminKeys200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ListAdminKeys200ResponseDataFromJSON(json['data']),
    };
}

export function ListAdminKeys200ResponseToJSON(json: any): ListAdminKeys200Response {
    return ListAdminKeys200ResponseToJSONTyped(json, false);
}

export function ListAdminKeys200ResponseToJSONTyped(value?: ListAdminKeys200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListAdminKeys200ResponseDataToJSON(value['data']),
    };
}

