/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NearTransferDataActionsInner } from './NearTransferDataActionsInner';
import {
    NearTransferDataActionsInnerFromJSON,
    NearTransferDataActionsInnerFromJSONTyped,
    NearTransferDataActionsInnerToJSON,
    NearTransferDataActionsInnerToJSONTyped,
} from './NearTransferDataActionsInner';

/**
 * 
 * @export
 * @interface NearTransferData
 */
export interface NearTransferData {
    /**
     * 
     * @type {string}
     * @memberof NearTransferData
     */
    type: NearTransferDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NearTransferData
     */
    receiverId: string;
    /**
     * 
     * @type {Array<NearTransferDataActionsInner>}
     * @memberof NearTransferData
     */
    actions: Array<NearTransferDataActionsInner>;
    /**
     * 
     * @type {string}
     * @memberof NearTransferData
     */
    tokenContract?: string;
}


/**
 * @export
 */
export const NearTransferDataTypeEnum = {
    NEAR: 'near'
} as const;
export type NearTransferDataTypeEnum = typeof NearTransferDataTypeEnum[keyof typeof NearTransferDataTypeEnum];


/**
 * Check if a given object implements the NearTransferData interface.
 */
export function instanceOfNearTransferData(value: object): value is NearTransferData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('receiverId' in value) || value['receiverId'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function NearTransferDataFromJSON(json: any): NearTransferData {
    return NearTransferDataFromJSONTyped(json, false);
}

export function NearTransferDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearTransferData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'receiverId': json['receiverId'],
        'actions': ((json['actions'] as Array<any>).map(NearTransferDataActionsInnerFromJSON)),
        'tokenContract': json['tokenContract'] == null ? undefined : json['tokenContract'],
    };
}

export function NearTransferDataToJSON(json: any): NearTransferData {
    return NearTransferDataToJSONTyped(json, false);
}

export function NearTransferDataToJSONTyped(value?: NearTransferData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'receiverId': value['receiverId'],
        'actions': ((value['actions'] as Array<any>).map(NearTransferDataActionsInnerToJSON)),
        'tokenContract': value['tokenContract'],
    };
}

