/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NearTransferDataActionsInner
 */
export interface NearTransferDataActionsInner {
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    type: NearTransferDataActionsInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    methodName?: string;
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    args?: string;
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    gas?: string;
    /**
     * 
     * @type {string}
     * @memberof NearTransferDataActionsInner
     */
    deposit?: string;
}


/**
 * @export
 */
export const NearTransferDataActionsInnerTypeEnum = {
    TRANSFER: 'Transfer',
    FUNCTION_CALL: 'FunctionCall'
} as const;
export type NearTransferDataActionsInnerTypeEnum = typeof NearTransferDataActionsInnerTypeEnum[keyof typeof NearTransferDataActionsInnerTypeEnum];


/**
 * Check if a given object implements the NearTransferDataActionsInner interface.
 */
export function instanceOfNearTransferDataActionsInner(value: object): value is NearTransferDataActionsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NearTransferDataActionsInnerFromJSON(json: any): NearTransferDataActionsInner {
    return NearTransferDataActionsInnerFromJSONTyped(json, false);
}

export function NearTransferDataActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearTransferDataActionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'methodName': json['methodName'] == null ? undefined : json['methodName'],
        'args': json['args'] == null ? undefined : json['args'],
        'gas': json['gas'] == null ? undefined : json['gas'],
        'deposit': json['deposit'] == null ? undefined : json['deposit'],
    };
}

export function NearTransferDataActionsInnerToJSON(json: any): NearTransferDataActionsInner {
    return NearTransferDataActionsInnerToJSONTyped(json, false);
}

export function NearTransferDataActionsInnerToJSONTyped(value?: NearTransferDataActionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'amount': value['amount'],
        'methodName': value['methodName'],
        'args': value['args'],
        'gas': value['gas'],
        'deposit': value['deposit'],
    };
}

