/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivacyScore200ResponseData } from './PrivacyScore200ResponseData';
import {
    PrivacyScore200ResponseDataFromJSON,
    PrivacyScore200ResponseDataFromJSONTyped,
    PrivacyScore200ResponseDataToJSON,
    PrivacyScore200ResponseDataToJSONTyped,
} from './PrivacyScore200ResponseData';

/**
 * 
 * @export
 * @interface PrivacyScore200Response
 */
export interface PrivacyScore200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PrivacyScore200Response
     */
    success?: boolean;
    /**
     * 
     * @type {PrivacyScore200ResponseData}
     * @memberof PrivacyScore200Response
     */
    data?: PrivacyScore200ResponseData;
}

/**
 * Check if a given object implements the PrivacyScore200Response interface.
 */
export function instanceOfPrivacyScore200Response(value: object): value is PrivacyScore200Response {
    return true;
}

export function PrivacyScore200ResponseFromJSON(json: any): PrivacyScore200Response {
    return PrivacyScore200ResponseFromJSONTyped(json, false);
}

export function PrivacyScore200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyScore200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : PrivacyScore200ResponseDataFromJSON(json['data']),
    };
}

export function PrivacyScore200ResponseToJSON(json: any): PrivacyScore200Response {
    return PrivacyScore200ResponseToJSONTyped(json, false);
}

export function PrivacyScore200ResponseToJSONTyped(value?: PrivacyScore200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PrivacyScore200ResponseDataToJSON(value['data']),
    };
}

