/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivacyScore200ResponseDataFactors } from './PrivacyScore200ResponseDataFactors';
import {
    PrivacyScore200ResponseDataFactorsFromJSON,
    PrivacyScore200ResponseDataFactorsFromJSONTyped,
    PrivacyScore200ResponseDataFactorsToJSON,
    PrivacyScore200ResponseDataFactorsToJSONTyped,
} from './PrivacyScore200ResponseDataFactors';

/**
 * 
 * @export
 * @interface PrivacyScore200ResponseData
 */
export interface PrivacyScore200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof PrivacyScore200ResponseData
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof PrivacyScore200ResponseData
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof PrivacyScore200ResponseData
     */
    grade?: PrivacyScore200ResponseDataGradeEnum;
    /**
     * 
     * @type {number}
     * @memberof PrivacyScore200ResponseData
     */
    transactionsAnalyzed?: number;
    /**
     * 
     * @type {PrivacyScore200ResponseDataFactors}
     * @memberof PrivacyScore200ResponseData
     */
    factors?: PrivacyScore200ResponseDataFactors;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrivacyScore200ResponseData
     */
    recommendations?: Array<string>;
}


/**
 * @export
 */
export const PrivacyScore200ResponseDataGradeEnum = {
    A: 'A',
    B: 'B',
    C: 'C',
    D: 'D',
    F: 'F'
} as const;
export type PrivacyScore200ResponseDataGradeEnum = typeof PrivacyScore200ResponseDataGradeEnum[keyof typeof PrivacyScore200ResponseDataGradeEnum];


/**
 * Check if a given object implements the PrivacyScore200ResponseData interface.
 */
export function instanceOfPrivacyScore200ResponseData(value: object): value is PrivacyScore200ResponseData {
    return true;
}

export function PrivacyScore200ResponseDataFromJSON(json: any): PrivacyScore200ResponseData {
    return PrivacyScore200ResponseDataFromJSONTyped(json, false);
}

export function PrivacyScore200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyScore200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'score': json['score'] == null ? undefined : json['score'],
        'grade': json['grade'] == null ? undefined : json['grade'],
        'transactionsAnalyzed': json['transactionsAnalyzed'] == null ? undefined : json['transactionsAnalyzed'],
        'factors': json['factors'] == null ? undefined : PrivacyScore200ResponseDataFactorsFromJSON(json['factors']),
        'recommendations': json['recommendations'] == null ? undefined : json['recommendations'],
    };
}

export function PrivacyScore200ResponseDataToJSON(json: any): PrivacyScore200ResponseData {
    return PrivacyScore200ResponseDataToJSONTyped(json, false);
}

export function PrivacyScore200ResponseDataToJSONTyped(value?: PrivacyScore200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'score': value['score'],
        'grade': value['grade'],
        'transactionsAnalyzed': value['transactionsAnalyzed'],
        'factors': PrivacyScore200ResponseDataFactorsToJSON(value['factors']),
        'recommendations': value['recommendations'],
    };
}

