/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofsValidityGenerateRequest
 */
export interface ProofsValidityGenerateRequest {
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    intentHash: string;
    /**
     * 
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    senderAddress: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    senderBlinding: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    senderSecret: string;
    /**
     * 
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    authorizationSignature: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ProofsValidityGenerateRequest
     */
    nonce: string;
    /**
     * 
     * @type {number}
     * @memberof ProofsValidityGenerateRequest
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ProofsValidityGenerateRequest
     */
    expiry: number;
}

/**
 * Check if a given object implements the ProofsValidityGenerateRequest interface.
 */
export function instanceOfProofsValidityGenerateRequest(value: object): value is ProofsValidityGenerateRequest {
    if (!('intentHash' in value) || value['intentHash'] === undefined) return false;
    if (!('senderAddress' in value) || value['senderAddress'] === undefined) return false;
    if (!('senderBlinding' in value) || value['senderBlinding'] === undefined) return false;
    if (!('senderSecret' in value) || value['senderSecret'] === undefined) return false;
    if (!('authorizationSignature' in value) || value['authorizationSignature'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('expiry' in value) || value['expiry'] === undefined) return false;
    return true;
}

export function ProofsValidityGenerateRequestFromJSON(json: any): ProofsValidityGenerateRequest {
    return ProofsValidityGenerateRequestFromJSONTyped(json, false);
}

export function ProofsValidityGenerateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsValidityGenerateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'intentHash': json['intentHash'],
        'senderAddress': json['senderAddress'],
        'senderBlinding': json['senderBlinding'],
        'senderSecret': json['senderSecret'],
        'authorizationSignature': json['authorizationSignature'],
        'nonce': json['nonce'],
        'timestamp': json['timestamp'],
        'expiry': json['expiry'],
    };
}

export function ProofsValidityGenerateRequestToJSON(json: any): ProofsValidityGenerateRequest {
    return ProofsValidityGenerateRequestToJSONTyped(json, false);
}

export function ProofsValidityGenerateRequestToJSONTyped(value?: ProofsValidityGenerateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'intentHash': value['intentHash'],
        'senderAddress': value['senderAddress'],
        'senderBlinding': value['senderBlinding'],
        'senderSecret': value['senderSecret'],
        'authorizationSignature': value['authorizationSignature'],
        'nonce': value['nonce'],
        'timestamp': value['timestamp'],
        'expiry': value['expiry'],
    };
}

