/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofsFundingGenerate200ResponseDataProof
 */
export interface ProofsFundingGenerate200ResponseDataProof {
    /**
     * 
     * @type {string}
     * @memberof ProofsFundingGenerate200ResponseDataProof
     */
    type?: ProofsFundingGenerate200ResponseDataProofTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProofsFundingGenerate200ResponseDataProof
     */
    proof?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProofsFundingGenerate200ResponseDataProof
     */
    publicInputs?: Array<string>;
}


/**
 * @export
 */
export const ProofsFundingGenerate200ResponseDataProofTypeEnum = {
    FUNDING: 'funding'
} as const;
export type ProofsFundingGenerate200ResponseDataProofTypeEnum = typeof ProofsFundingGenerate200ResponseDataProofTypeEnum[keyof typeof ProofsFundingGenerate200ResponseDataProofTypeEnum];


/**
 * Check if a given object implements the ProofsFundingGenerate200ResponseDataProof interface.
 */
export function instanceOfProofsFundingGenerate200ResponseDataProof(value: object): value is ProofsFundingGenerate200ResponseDataProof {
    return true;
}

export function ProofsFundingGenerate200ResponseDataProofFromJSON(json: any): ProofsFundingGenerate200ResponseDataProof {
    return ProofsFundingGenerate200ResponseDataProofFromJSONTyped(json, false);
}

export function ProofsFundingGenerate200ResponseDataProofFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsFundingGenerate200ResponseDataProof {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'proof': json['proof'] == null ? undefined : json['proof'],
        'publicInputs': json['publicInputs'] == null ? undefined : json['publicInputs'],
    };
}

export function ProofsFundingGenerate200ResponseDataProofToJSON(json: any): ProofsFundingGenerate200ResponseDataProof {
    return ProofsFundingGenerate200ResponseDataProofToJSONTyped(json, false);
}

export function ProofsFundingGenerate200ResponseDataProofToJSONTyped(value?: ProofsFundingGenerate200ResponseDataProof | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'proof': value['proof'],
        'publicInputs': value['publicInputs'],
    };
}

