/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofsFundingVerifyRequest
 */
export interface ProofsFundingVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof ProofsFundingVerifyRequest
     */
    type: ProofsFundingVerifyRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProofsFundingVerifyRequest
     */
    proof: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProofsFundingVerifyRequest
     */
    publicInputs: Array<string>;
}


/**
 * @export
 */
export const ProofsFundingVerifyRequestTypeEnum = {
    FUNDING: 'funding'
} as const;
export type ProofsFundingVerifyRequestTypeEnum = typeof ProofsFundingVerifyRequestTypeEnum[keyof typeof ProofsFundingVerifyRequestTypeEnum];


/**
 * Check if a given object implements the ProofsFundingVerifyRequest interface.
 */
export function instanceOfProofsFundingVerifyRequest(value: object): value is ProofsFundingVerifyRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('proof' in value) || value['proof'] === undefined) return false;
    if (!('publicInputs' in value) || value['publicInputs'] === undefined) return false;
    return true;
}

export function ProofsFundingVerifyRequestFromJSON(json: any): ProofsFundingVerifyRequest {
    return ProofsFundingVerifyRequestFromJSONTyped(json, false);
}

export function ProofsFundingVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsFundingVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'proof': json['proof'],
        'publicInputs': json['publicInputs'],
    };
}

export function ProofsFundingVerifyRequestToJSON(json: any): ProofsFundingVerifyRequest {
    return ProofsFundingVerifyRequestToJSONTyped(json, false);
}

export function ProofsFundingVerifyRequestToJSONTyped(value?: ProofsFundingVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'proof': value['proof'],
        'publicInputs': value['publicInputs'],
    };
}

