/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofsFulfillmentVerifyRequest
 */
export interface ProofsFulfillmentVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof ProofsFulfillmentVerifyRequest
     */
    type: ProofsFulfillmentVerifyRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProofsFulfillmentVerifyRequest
     */
    proof: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProofsFulfillmentVerifyRequest
     */
    publicInputs: Array<string>;
}


/**
 * @export
 */
export const ProofsFulfillmentVerifyRequestTypeEnum = {
    FULFILLMENT: 'fulfillment'
} as const;
export type ProofsFulfillmentVerifyRequestTypeEnum = typeof ProofsFulfillmentVerifyRequestTypeEnum[keyof typeof ProofsFulfillmentVerifyRequestTypeEnum];


/**
 * Check if a given object implements the ProofsFulfillmentVerifyRequest interface.
 */
export function instanceOfProofsFulfillmentVerifyRequest(value: object): value is ProofsFulfillmentVerifyRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('proof' in value) || value['proof'] === undefined) return false;
    if (!('publicInputs' in value) || value['publicInputs'] === undefined) return false;
    return true;
}

export function ProofsFulfillmentVerifyRequestFromJSON(json: any): ProofsFulfillmentVerifyRequest {
    return ProofsFulfillmentVerifyRequestFromJSONTyped(json, false);
}

export function ProofsFulfillmentVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsFulfillmentVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'proof': json['proof'],
        'publicInputs': json['publicInputs'],
    };
}

export function ProofsFulfillmentVerifyRequestToJSON(json: any): ProofsFulfillmentVerifyRequest {
    return ProofsFulfillmentVerifyRequestToJSONTyped(json, false);
}

export function ProofsFulfillmentVerifyRequestToJSONTyped(value?: ProofsFulfillmentVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'proof': value['proof'],
        'publicInputs': value['publicInputs'],
    };
}

