/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProofsValidityGenerate200ResponseData } from './ProofsValidityGenerate200ResponseData';
import {
    ProofsValidityGenerate200ResponseDataFromJSON,
    ProofsValidityGenerate200ResponseDataFromJSONTyped,
    ProofsValidityGenerate200ResponseDataToJSON,
    ProofsValidityGenerate200ResponseDataToJSONTyped,
} from './ProofsValidityGenerate200ResponseData';

/**
 * 
 * @export
 * @interface ProofsValidityGenerate200Response
 */
export interface ProofsValidityGenerate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ProofsValidityGenerate200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ProofsValidityGenerate200ResponseData}
     * @memberof ProofsValidityGenerate200Response
     */
    data?: ProofsValidityGenerate200ResponseData;
}

/**
 * Check if a given object implements the ProofsValidityGenerate200Response interface.
 */
export function instanceOfProofsValidityGenerate200Response(value: object): value is ProofsValidityGenerate200Response {
    return true;
}

export function ProofsValidityGenerate200ResponseFromJSON(json: any): ProofsValidityGenerate200Response {
    return ProofsValidityGenerate200ResponseFromJSONTyped(json, false);
}

export function ProofsValidityGenerate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsValidityGenerate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ProofsValidityGenerate200ResponseDataFromJSON(json['data']),
    };
}

export function ProofsValidityGenerate200ResponseToJSON(json: any): ProofsValidityGenerate200Response {
    return ProofsValidityGenerate200ResponseToJSONTyped(json, false);
}

export function ProofsValidityGenerate200ResponseToJSONTyped(value?: ProofsValidityGenerate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ProofsValidityGenerate200ResponseDataToJSON(value['data']),
    };
}

