/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanPaymentsBatch200ResponseDataSummary
 */
export interface ScanPaymentsBatch200ResponseDataSummary {
    /**
     * 
     * @type {number}
     * @memberof ScanPaymentsBatch200ResponseDataSummary
     */
    totalKeyPairs?: number;
    /**
     * 
     * @type {number}
     * @memberof ScanPaymentsBatch200ResponseDataSummary
     */
    totalPaymentsFound?: number;
    /**
     * 
     * @type {number}
     * @memberof ScanPaymentsBatch200ResponseDataSummary
     */
    transactionsScanned?: number;
}

/**
 * Check if a given object implements the ScanPaymentsBatch200ResponseDataSummary interface.
 */
export function instanceOfScanPaymentsBatch200ResponseDataSummary(value: object): value is ScanPaymentsBatch200ResponseDataSummary {
    return true;
}

export function ScanPaymentsBatch200ResponseDataSummaryFromJSON(json: any): ScanPaymentsBatch200ResponseDataSummary {
    return ScanPaymentsBatch200ResponseDataSummaryFromJSONTyped(json, false);
}

export function ScanPaymentsBatch200ResponseDataSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanPaymentsBatch200ResponseDataSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalKeyPairs': json['totalKeyPairs'] == null ? undefined : json['totalKeyPairs'],
        'totalPaymentsFound': json['totalPaymentsFound'] == null ? undefined : json['totalPaymentsFound'],
        'transactionsScanned': json['transactionsScanned'] == null ? undefined : json['transactionsScanned'],
    };
}

export function ScanPaymentsBatch200ResponseDataSummaryToJSON(json: any): ScanPaymentsBatch200ResponseDataSummary {
    return ScanPaymentsBatch200ResponseDataSummaryToJSONTyped(json, false);
}

export function ScanPaymentsBatch200ResponseDataSummaryToJSONTyped(value?: ScanPaymentsBatch200ResponseDataSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalKeyPairs': value['totalKeyPairs'],
        'totalPaymentsFound': value['totalPaymentsFound'],
        'transactionsScanned': value['transactionsScanned'],
    };
}

