/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StealthGenerateBatch200ResponseData } from './StealthGenerateBatch200ResponseData';
import {
    StealthGenerateBatch200ResponseDataFromJSON,
    StealthGenerateBatch200ResponseDataFromJSONTyped,
    StealthGenerateBatch200ResponseDataToJSON,
    StealthGenerateBatch200ResponseDataToJSONTyped,
} from './StealthGenerateBatch200ResponseData';

/**
 * 
 * @export
 * @interface StealthGenerateBatch200Response
 */
export interface StealthGenerateBatch200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StealthGenerateBatch200Response
     */
    success?: boolean;
    /**
     * 
     * @type {StealthGenerateBatch200ResponseData}
     * @memberof StealthGenerateBatch200Response
     */
    data?: StealthGenerateBatch200ResponseData;
}

/**
 * Check if a given object implements the StealthGenerateBatch200Response interface.
 */
export function instanceOfStealthGenerateBatch200Response(value: object): value is StealthGenerateBatch200Response {
    return true;
}

export function StealthGenerateBatch200ResponseFromJSON(json: any): StealthGenerateBatch200Response {
    return StealthGenerateBatch200ResponseFromJSONTyped(json, false);
}

export function StealthGenerateBatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StealthGenerateBatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : StealthGenerateBatch200ResponseDataFromJSON(json['data']),
    };
}

export function StealthGenerateBatch200ResponseToJSON(json: any): StealthGenerateBatch200Response {
    return StealthGenerateBatch200ResponseToJSONTyped(json, false);
}

export function StealthGenerateBatch200ResponseToJSONTyped(value?: StealthGenerateBatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': StealthGenerateBatch200ResponseDataToJSON(value['data']),
    };
}

