/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StealthGenerate200ResponseData } from './StealthGenerate200ResponseData';
import {
    StealthGenerate200ResponseDataFromJSON,
    StealthGenerate200ResponseDataFromJSONTyped,
    StealthGenerate200ResponseDataToJSON,
    StealthGenerate200ResponseDataToJSONTyped,
} from './StealthGenerate200ResponseData';

/**
 * 
 * @export
 * @interface StealthGenerate200Response
 */
export interface StealthGenerate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StealthGenerate200Response
     */
    success?: boolean;
    /**
     * 
     * @type {StealthGenerate200ResponseData}
     * @memberof StealthGenerate200Response
     */
    data?: StealthGenerate200ResponseData;
}

/**
 * Check if a given object implements the StealthGenerate200Response interface.
 */
export function instanceOfStealthGenerate200Response(value: object): value is StealthGenerate200Response {
    return true;
}

export function StealthGenerate200ResponseFromJSON(json: any): StealthGenerate200Response {
    return StealthGenerate200ResponseFromJSONTyped(json, false);
}

export function StealthGenerate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StealthGenerate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : StealthGenerate200ResponseDataFromJSON(json['data']),
    };
}

export function StealthGenerate200ResponseToJSON(json: any): StealthGenerate200Response {
    return StealthGenerate200ResponseToJSONTyped(json, false);
}

export function StealthGenerate200ResponseToJSONTyped(value?: StealthGenerate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': StealthGenerate200ResponseDataToJSON(value['data']),
    };
}

