/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StealthCheck200ResponseData } from './StealthCheck200ResponseData';
import {
    StealthCheck200ResponseDataFromJSON,
    StealthCheck200ResponseDataFromJSONTyped,
    StealthCheck200ResponseDataToJSON,
    StealthCheck200ResponseDataToJSONTyped,
} from './StealthCheck200ResponseData';

/**
 * 
 * @export
 * @interface StealthCheck200Response
 */
export interface StealthCheck200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StealthCheck200Response
     */
    success?: boolean;
    /**
     * 
     * @type {StealthCheck200ResponseData}
     * @memberof StealthCheck200Response
     */
    data?: StealthCheck200ResponseData;
}

/**
 * Check if a given object implements the StealthCheck200Response interface.
 */
export function instanceOfStealthCheck200Response(value: object): value is StealthCheck200Response {
    return true;
}

export function StealthCheck200ResponseFromJSON(json: any): StealthCheck200Response {
    return StealthCheck200ResponseFromJSONTyped(json, false);
}

export function StealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StealthCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : StealthCheck200ResponseDataFromJSON(json['data']),
    };
}

export function StealthCheck200ResponseToJSON(json: any): StealthCheck200Response {
    return StealthCheck200ResponseToJSONTyped(json, false);
}

export function StealthCheck200ResponseToJSONTyped(value?: StealthCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': StealthCheck200ResponseDataToJSON(value['data']),
    };
}

