/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferPrivate422ResponseError } from './TransferPrivate422ResponseError';
import {
    TransferPrivate422ResponseErrorFromJSON,
    TransferPrivate422ResponseErrorFromJSONTyped,
    TransferPrivate422ResponseErrorToJSON,
    TransferPrivate422ResponseErrorToJSONTyped,
} from './TransferPrivate422ResponseError';

/**
 * 
 * @export
 * @interface TransferPrivate422Response
 */
export interface TransferPrivate422Response {
    /**
     * 
     * @type {boolean}
     * @memberof TransferPrivate422Response
     */
    success?: TransferPrivate422ResponseSuccessEnum;
    /**
     * 
     * @type {TransferPrivate422ResponseError}
     * @memberof TransferPrivate422Response
     */
    error?: TransferPrivate422ResponseError;
}


/**
 * @export
 */
export const TransferPrivate422ResponseSuccessEnum = {
    FALSE: false
} as const;
export type TransferPrivate422ResponseSuccessEnum = typeof TransferPrivate422ResponseSuccessEnum[keyof typeof TransferPrivate422ResponseSuccessEnum];


/**
 * Check if a given object implements the TransferPrivate422Response interface.
 */
export function instanceOfTransferPrivate422Response(value: object): value is TransferPrivate422Response {
    return true;
}

export function TransferPrivate422ResponseFromJSON(json: any): TransferPrivate422Response {
    return TransferPrivate422ResponseFromJSONTyped(json, false);
}

export function TransferPrivate422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferPrivate422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : TransferPrivate422ResponseErrorFromJSON(json['error']),
    };
}

export function TransferPrivate422ResponseToJSON(json: any): TransferPrivate422Response {
    return TransferPrivate422ResponseToJSONTyped(json, false);
}

export function TransferPrivate422ResponseToJSONTyped(value?: TransferPrivate422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': TransferPrivate422ResponseErrorToJSON(value['error']),
    };
}

