/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferClaim200ResponseData
 */
export interface TransferClaim200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof TransferClaim200ResponseData
     */
    txSignature?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferClaim200ResponseData
     */
    destinationAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferClaim200ResponseData
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferClaim200ResponseData
     */
    explorerUrl?: string;
}

/**
 * Check if a given object implements the TransferClaim200ResponseData interface.
 */
export function instanceOfTransferClaim200ResponseData(value: object): value is TransferClaim200ResponseData {
    return true;
}

export function TransferClaim200ResponseDataFromJSON(json: any): TransferClaim200ResponseData {
    return TransferClaim200ResponseDataFromJSONTyped(json, false);
}

export function TransferClaim200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferClaim200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'txSignature': json['txSignature'] == null ? undefined : json['txSignature'],
        'destinationAddress': json['destinationAddress'] == null ? undefined : json['destinationAddress'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'explorerUrl': json['explorerUrl'] == null ? undefined : json['explorerUrl'],
    };
}

export function TransferClaim200ResponseDataToJSON(json: any): TransferClaim200ResponseData {
    return TransferClaim200ResponseDataToJSONTyped(json, false);
}

export function TransferClaim200ResponseDataToJSONTyped(value?: TransferClaim200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txSignature': value['txSignature'],
        'destinationAddress': value['destinationAddress'],
        'amount': value['amount'],
        'explorerUrl': value['explorerUrl'],
    };
}

