/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferShield200ResponseData
 */
export interface TransferShield200ResponseData {
    /**
     * Base64-encoded unsigned transaction
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    transaction?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    stealthAddress?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    ephemeralPublicKey?: string;
    /**
     * 
     * @type {number}
     * @memberof TransferShield200ResponseData
     */
    viewTag?: number;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    commitment?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    blindingFactor?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    viewingKeyHash?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof TransferShield200ResponseData
     */
    sharedSecret?: string;
}

/**
 * Check if a given object implements the TransferShield200ResponseData interface.
 */
export function instanceOfTransferShield200ResponseData(value: object): value is TransferShield200ResponseData {
    return true;
}

export function TransferShield200ResponseDataFromJSON(json: any): TransferShield200ResponseData {
    return TransferShield200ResponseDataFromJSONTyped(json, false);
}

export function TransferShield200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferShield200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': json['transaction'] == null ? undefined : json['transaction'],
        'stealthAddress': json['stealthAddress'] == null ? undefined : json['stealthAddress'],
        'ephemeralPublicKey': json['ephemeralPublicKey'] == null ? undefined : json['ephemeralPublicKey'],
        'viewTag': json['viewTag'] == null ? undefined : json['viewTag'],
        'commitment': json['commitment'] == null ? undefined : json['commitment'],
        'blindingFactor': json['blindingFactor'] == null ? undefined : json['blindingFactor'],
        'viewingKeyHash': json['viewingKeyHash'] == null ? undefined : json['viewingKeyHash'],
        'sharedSecret': json['sharedSecret'] == null ? undefined : json['sharedSecret'],
    };
}

export function TransferShield200ResponseDataToJSON(json: any): TransferShield200ResponseData {
    return TransferShield200ResponseDataToJSONTyped(json, false);
}

export function TransferShield200ResponseDataToJSONTyped(value?: TransferShield200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': value['transaction'],
        'stealthAddress': value['stealthAddress'],
        'ephemeralPublicKey': value['ephemeralPublicKey'],
        'viewTag': value['viewTag'],
        'commitment': value['commitment'],
        'blindingFactor': value['blindingFactor'],
        'viewingKeyHash': value['viewingKeyHash'],
        'sharedSecret': value['sharedSecret'],
    };
}

