/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferClaim200ResponseData } from './TransferClaim200ResponseData';
import {
    TransferClaim200ResponseDataFromJSON,
    TransferClaim200ResponseDataFromJSONTyped,
    TransferClaim200ResponseDataToJSON,
    TransferClaim200ResponseDataToJSONTyped,
} from './TransferClaim200ResponseData';

/**
 * 
 * @export
 * @interface TransferClaim200Response
 */
export interface TransferClaim200Response {
    /**
     * 
     * @type {boolean}
     * @memberof TransferClaim200Response
     */
    success?: boolean;
    /**
     * 
     * @type {TransferClaim200ResponseData}
     * @memberof TransferClaim200Response
     */
    data?: TransferClaim200ResponseData;
}

/**
 * Check if a given object implements the TransferClaim200Response interface.
 */
export function instanceOfTransferClaim200Response(value: object): value is TransferClaim200Response {
    return true;
}

export function TransferClaim200ResponseFromJSON(json: any): TransferClaim200Response {
    return TransferClaim200ResponseFromJSONTyped(json, false);
}

export function TransferClaim200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferClaim200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : TransferClaim200ResponseDataFromJSON(json['data']),
    };
}

export function TransferClaim200ResponseToJSON(json: any): TransferClaim200Response {
    return TransferClaim200ResponseToJSONTyped(json, false);
}

export function TransferClaim200ResponseToJSONTyped(value?: TransferClaim200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TransferClaim200ResponseDataToJSON(value['data']),
    };
}

