/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewingKeyDerive200ResponseDataDerivedFrom
 */
export interface ViewingKeyDerive200ResponseDataDerivedFrom {
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ViewingKeyDerive200ResponseDataDerivedFrom
     */
    parentHash?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyDerive200ResponseDataDerivedFrom
     */
    parentPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyDerive200ResponseDataDerivedFrom
     */
    childPath?: string;
}

/**
 * Check if a given object implements the ViewingKeyDerive200ResponseDataDerivedFrom interface.
 */
export function instanceOfViewingKeyDerive200ResponseDataDerivedFrom(value: object): value is ViewingKeyDerive200ResponseDataDerivedFrom {
    return true;
}

export function ViewingKeyDerive200ResponseDataDerivedFromFromJSON(json: any): ViewingKeyDerive200ResponseDataDerivedFrom {
    return ViewingKeyDerive200ResponseDataDerivedFromFromJSONTyped(json, false);
}

export function ViewingKeyDerive200ResponseDataDerivedFromFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewingKeyDerive200ResponseDataDerivedFrom {
    if (json == null) {
        return json;
    }
    return {
        
        'parentHash': json['parentHash'] == null ? undefined : json['parentHash'],
        'parentPath': json['parentPath'] == null ? undefined : json['parentPath'],
        'childPath': json['childPath'] == null ? undefined : json['childPath'],
    };
}

export function ViewingKeyDerive200ResponseDataDerivedFromToJSON(json: any): ViewingKeyDerive200ResponseDataDerivedFrom {
    return ViewingKeyDerive200ResponseDataDerivedFromToJSONTyped(json, false);
}

export function ViewingKeyDerive200ResponseDataDerivedFromToJSONTyped(value?: ViewingKeyDerive200ResponseDataDerivedFrom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentHash': value['parentHash'],
        'parentPath': value['parentPath'],
        'childPath': value['childPath'],
    };
}

