/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewingKeyDecryptRequestEncrypted } from './ViewingKeyDecryptRequestEncrypted';
import {
    ViewingKeyDecryptRequestEncryptedFromJSON,
    ViewingKeyDecryptRequestEncryptedFromJSONTyped,
    ViewingKeyDecryptRequestEncryptedToJSON,
    ViewingKeyDecryptRequestEncryptedToJSONTyped,
} from './ViewingKeyDecryptRequestEncrypted';
import type { ViewingKey } from './ViewingKey';
import {
    ViewingKeyFromJSON,
    ViewingKeyFromJSONTyped,
    ViewingKeyToJSON,
    ViewingKeyToJSONTyped,
} from './ViewingKey';

/**
 * 
 * @export
 * @interface ViewingKeyDecryptRequest
 */
export interface ViewingKeyDecryptRequest {
    /**
     * 
     * @type {ViewingKey}
     * @memberof ViewingKeyDecryptRequest
     */
    viewingKey: ViewingKey;
    /**
     * 
     * @type {ViewingKeyDecryptRequestEncrypted}
     * @memberof ViewingKeyDecryptRequest
     */
    encrypted: ViewingKeyDecryptRequestEncrypted;
}

/**
 * Check if a given object implements the ViewingKeyDecryptRequest interface.
 */
export function instanceOfViewingKeyDecryptRequest(value: object): value is ViewingKeyDecryptRequest {
    if (!('viewingKey' in value) || value['viewingKey'] === undefined) return false;
    if (!('encrypted' in value) || value['encrypted'] === undefined) return false;
    return true;
}

export function ViewingKeyDecryptRequestFromJSON(json: any): ViewingKeyDecryptRequest {
    return ViewingKeyDecryptRequestFromJSONTyped(json, false);
}

export function ViewingKeyDecryptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewingKeyDecryptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'viewingKey': ViewingKeyFromJSON(json['viewingKey']),
        'encrypted': ViewingKeyDecryptRequestEncryptedFromJSON(json['encrypted']),
    };
}

export function ViewingKeyDecryptRequestToJSON(json: any): ViewingKeyDecryptRequest {
    return ViewingKeyDecryptRequestToJSONTyped(json, false);
}

export function ViewingKeyDecryptRequestToJSONTyped(value?: ViewingKeyDecryptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'viewingKey': ViewingKeyToJSON(value['viewingKey']),
        'encrypted': ViewingKeyDecryptRequestEncryptedToJSON(value['encrypted']),
    };
}

