/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewingKeyVerifyHierarchy200ResponseData
 */
export interface ViewingKeyVerifyHierarchy200ResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof ViewingKeyVerifyHierarchy200ResponseData
     */
    valid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyVerifyHierarchy200ResponseData
     */
    expectedPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyVerifyHierarchy200ResponseData
     */
    actualPath?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ViewingKeyVerifyHierarchy200ResponseData
     */
    parentHash?: string;
    /**
     * 0x-prefixed 32-byte hex string
     * @type {string}
     * @memberof ViewingKeyVerifyHierarchy200ResponseData
     */
    childHash?: string;
}

/**
 * Check if a given object implements the ViewingKeyVerifyHierarchy200ResponseData interface.
 */
export function instanceOfViewingKeyVerifyHierarchy200ResponseData(value: object): value is ViewingKeyVerifyHierarchy200ResponseData {
    return true;
}

export function ViewingKeyVerifyHierarchy200ResponseDataFromJSON(json: any): ViewingKeyVerifyHierarchy200ResponseData {
    return ViewingKeyVerifyHierarchy200ResponseDataFromJSONTyped(json, false);
}

export function ViewingKeyVerifyHierarchy200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewingKeyVerifyHierarchy200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'] == null ? undefined : json['valid'],
        'expectedPath': json['expectedPath'] == null ? undefined : json['expectedPath'],
        'actualPath': json['actualPath'] == null ? undefined : json['actualPath'],
        'parentHash': json['parentHash'] == null ? undefined : json['parentHash'],
        'childHash': json['childHash'] == null ? undefined : json['childHash'],
    };
}

export function ViewingKeyVerifyHierarchy200ResponseDataToJSON(json: any): ViewingKeyVerifyHierarchy200ResponseData {
    return ViewingKeyVerifyHierarchy200ResponseDataToJSONTyped(json, false);
}

export function ViewingKeyVerifyHierarchy200ResponseDataToJSONTyped(value?: ViewingKeyVerifyHierarchy200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'expectedPath': value['expectedPath'],
        'actualPath': value['actualPath'],
        'parentHash': value['parentHash'],
        'childHash': value['childHash'],
    };
}

