/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewingKeyDiscloseRequestTransactionData
 */
export interface ViewingKeyDiscloseRequestTransactionData {
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyDiscloseRequestTransactionData
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyDiscloseRequestTransactionData
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof ViewingKeyDiscloseRequestTransactionData
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof ViewingKeyDiscloseRequestTransactionData
     */
    timestamp: number;
}

/**
 * Check if a given object implements the ViewingKeyDiscloseRequestTransactionData interface.
 */
export function instanceOfViewingKeyDiscloseRequestTransactionData(value: object): value is ViewingKeyDiscloseRequestTransactionData {
    if (!('sender' in value) || value['sender'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ViewingKeyDiscloseRequestTransactionDataFromJSON(json: any): ViewingKeyDiscloseRequestTransactionData {
    return ViewingKeyDiscloseRequestTransactionDataFromJSONTyped(json, false);
}

export function ViewingKeyDiscloseRequestTransactionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewingKeyDiscloseRequestTransactionData {
    if (json == null) {
        return json;
    }
    return {
        
        'sender': json['sender'],
        'recipient': json['recipient'],
        'amount': json['amount'],
        'timestamp': json['timestamp'],
    };
}

export function ViewingKeyDiscloseRequestTransactionDataToJSON(json: any): ViewingKeyDiscloseRequestTransactionData {
    return ViewingKeyDiscloseRequestTransactionDataToJSONTyped(json, false);
}

export function ViewingKeyDiscloseRequestTransactionDataToJSONTyped(value?: ViewingKeyDiscloseRequestTransactionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender': value['sender'],
        'recipient': value['recipient'],
        'amount': value['amount'],
        'timestamp': value['timestamp'],
    };
}

