/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewingKeyDecrypt200ResponseData } from './ViewingKeyDecrypt200ResponseData';
import {
    ViewingKeyDecrypt200ResponseDataFromJSON,
    ViewingKeyDecrypt200ResponseDataFromJSONTyped,
    ViewingKeyDecrypt200ResponseDataToJSON,
    ViewingKeyDecrypt200ResponseDataToJSONTyped,
} from './ViewingKeyDecrypt200ResponseData';

/**
 * 
 * @export
 * @interface ViewingKeyDecrypt200Response
 */
export interface ViewingKeyDecrypt200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ViewingKeyDecrypt200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ViewingKeyDecrypt200ResponseData}
     * @memberof ViewingKeyDecrypt200Response
     */
    data?: ViewingKeyDecrypt200ResponseData;
}

/**
 * Check if a given object implements the ViewingKeyDecrypt200Response interface.
 */
export function instanceOfViewingKeyDecrypt200Response(value: object): value is ViewingKeyDecrypt200Response {
    return true;
}

export function ViewingKeyDecrypt200ResponseFromJSON(json: any): ViewingKeyDecrypt200Response {
    return ViewingKeyDecrypt200ResponseFromJSONTyped(json, false);
}

export function ViewingKeyDecrypt200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewingKeyDecrypt200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ViewingKeyDecrypt200ResponseDataFromJSON(json['data']),
    };
}

export function ViewingKeyDecrypt200ResponseToJSON(json: any): ViewingKeyDecrypt200Response {
    return ViewingKeyDecrypt200ResponseToJSONTyped(json, false);
}

export function ViewingKeyDecrypt200ResponseToJSONTyped(value?: ViewingKeyDecrypt200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewingKeyDecrypt200ResponseDataToJSON(value['data']),
    };
}

