/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsHealth200ResponseDataHealth {
    #[serde(rename = "circuitState", skip_serializing_if = "Option::is_none")]
    pub circuit_state: Option<CircuitState>,
    #[serde(rename = "isHealthy", skip_serializing_if = "Option::is_none")]
    pub is_healthy: Option<bool>,
    #[serde(rename = "consecutiveFailures", skip_serializing_if = "Option::is_none")]
    pub consecutive_failures: Option<i32>,
    #[serde(rename = "consecutiveSuccesses", skip_serializing_if = "Option::is_none")]
    pub consecutive_successes: Option<i32>,
    #[serde(rename = "lastChecked", skip_serializing_if = "Option::is_none")]
    pub last_checked: Option<i32>,
    #[serde(rename = "lastFailureReason", skip_serializing_if = "Option::is_none")]
    pub last_failure_reason: Option<String>,
}

impl BackendsHealth200ResponseDataHealth {
    pub fn new() -> BackendsHealth200ResponseDataHealth {
        BackendsHealth200ResponseDataHealth {
            circuit_state: None,
            is_healthy: None,
            consecutive_failures: None,
            consecutive_successes: None,
            last_checked: None,
            last_failure_reason: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitState {
    #[serde(rename = "closed")]
    Closed,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "half-open")]
    HalfOpen,
}

impl Default for CircuitState {
    fn default() -> CircuitState {
        Self::Closed
    }
}

