/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsCompareRequest {
    /// Type of privacy operation to compare backends for
    #[serde(rename = "operation")]
    pub operation: Operation,
    /// Target blockchain (default: solana)
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
    /// Transaction amount in smallest units
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// Factor to prioritize in scoring (adjusts weights to 60%)
    #[serde(rename = "prioritize", skip_serializing_if = "Option::is_none")]
    pub prioritize: Option<Prioritize>,
}

impl BackendsCompareRequest {
    pub fn new(operation: Operation) -> BackendsCompareRequest {
        BackendsCompareRequest {
            operation,
            chain: None,
            amount: None,
            prioritize: None,
        }
    }
}
/// Type of privacy operation to compare backends for
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "stealth_privacy")]
    StealthPrivacy,
    #[serde(rename = "encrypted_compute")]
    EncryptedCompute,
    #[serde(rename = "compliance_audit")]
    ComplianceAudit,
}

impl Default for Operation {
    fn default() -> Operation {
        Self::StealthPrivacy
    }
}
/// Factor to prioritize in scoring (adjusts weights to 60%)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Prioritize {
    #[serde(rename = "cost")]
    Cost,
    #[serde(rename = "speed")]
    Speed,
    #[serde(rename = "privacy")]
    Privacy,
}

impl Default for Prioritize {
    fn default() -> Prioritize {
        Self::Cost
    }
}

