/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsList200ResponseDataBackendsInnerCapabilities {
    #[serde(rename = "hiddenAmount", skip_serializing_if = "Option::is_none")]
    pub hidden_amount: Option<bool>,
    #[serde(rename = "hiddenSender", skip_serializing_if = "Option::is_none")]
    pub hidden_sender: Option<bool>,
    #[serde(rename = "hiddenRecipient", skip_serializing_if = "Option::is_none")]
    pub hidden_recipient: Option<bool>,
    #[serde(rename = "hiddenCompute", skip_serializing_if = "Option::is_none")]
    pub hidden_compute: Option<bool>,
    #[serde(rename = "complianceSupport", skip_serializing_if = "Option::is_none")]
    pub compliance_support: Option<bool>,
    #[serde(rename = "setupRequired", skip_serializing_if = "Option::is_none")]
    pub setup_required: Option<bool>,
    #[serde(rename = "latencyEstimate", skip_serializing_if = "Option::is_none")]
    pub latency_estimate: Option<LatencyEstimate>,
    #[serde(rename = "supportedTokens", skip_serializing_if = "Option::is_none")]
    pub supported_tokens: Option<SupportedTokens>,
    /// BigInt as string
    #[serde(rename = "minAmount", skip_serializing_if = "Option::is_none")]
    pub min_amount: Option<String>,
    /// BigInt as string
    #[serde(rename = "maxAmount", skip_serializing_if = "Option::is_none")]
    pub max_amount: Option<String>,
}

impl BackendsList200ResponseDataBackendsInnerCapabilities {
    pub fn new() -> BackendsList200ResponseDataBackendsInnerCapabilities {
        BackendsList200ResponseDataBackendsInnerCapabilities {
            hidden_amount: None,
            hidden_sender: None,
            hidden_recipient: None,
            hidden_compute: None,
            compliance_support: None,
            setup_required: None,
            latency_estimate: None,
            supported_tokens: None,
            min_amount: None,
            max_amount: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LatencyEstimate {
    #[serde(rename = "fast")]
    Fast,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "slow")]
    Slow,
}

impl Default for LatencyEstimate {
    fn default() -> LatencyEstimate {
        Self::Fast
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupportedTokens {
    #[serde(rename = "native")]
    Native,
    #[serde(rename = "spl")]
    Spl,
    #[serde(rename = "all")]
    All,
}

impl Default for SupportedTokens {
    fn default() -> SupportedTokens {
        Self::Native
    }
}

