/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComplianceDiscloseRequestAuditorVerification {
    #[serde(rename = "auditorKeyHash")]
    pub auditor_key_hash: String,
    #[serde(rename = "nonce")]
    pub nonce: String,
}

impl ComplianceDiscloseRequestAuditorVerification {
    pub fn new(auditor_key_hash: String, nonce: String) -> ComplianceDiscloseRequestAuditorVerification {
        ComplianceDiscloseRequestAuditorVerification {
            auditor_key_hash,
            nonce,
        }
    }
}

