/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeIncoCiphertexts200ResponseData {
    #[serde(rename = "computationId", skip_serializing_if = "Option::is_none")]
    pub computation_id: Option<String>,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<String>,
    #[serde(rename = "operandCount", skip_serializing_if = "Option::is_none")]
    pub operand_count: Option<i32>,
    #[serde(rename = "resultCiphertext", skip_serializing_if = "Option::is_none")]
    pub result_ciphertext: Option<String>,
    #[serde(rename = "noiseBudgetRemaining", skip_serializing_if = "Option::is_none")]
    pub noise_budget_remaining: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl ComputeIncoCiphertexts200ResponseData {
    pub fn new() -> ComputeIncoCiphertexts200ResponseData {
        ComputeIncoCiphertexts200ResponseData {
            computation_id: None,
            operation: None,
            scheme: None,
            operand_count: None,
            result_ciphertext: None,
            noise_budget_remaining: None,
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "completed")]
    Completed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Completed
    }
}

