/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBillingSubscriptionRequest {
    #[serde(rename = "plan")]
    pub plan: Plan,
}

impl CreateBillingSubscriptionRequest {
    pub fn new(plan: Plan) -> CreateBillingSubscriptionRequest {
        CreateBillingSubscriptionRequest {
            plan,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "enterprise")]
    Enterprise,
}

impl Default for Plan {
    fn default() -> Plan {
        Self::Free
    }
}

