/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequest {
    #[serde(rename = "defaults")]
    pub defaults: Box<models::CreateSessionRequestDefaults>,
    /// Session TTL in seconds (default: 3600, max: 86400)
    #[serde(rename = "ttlSeconds", skip_serializing_if = "Option::is_none")]
    pub ttl_seconds: Option<i32>,
}

impl CreateSessionRequest {
    pub fn new(defaults: models::CreateSessionRequestDefaults) -> CreateSessionRequest {
        CreateSessionRequest {
            defaults: Box::new(defaults),
            ttl_seconds: None,
        }
    }
}

