/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptBallot200ResponseData {
    /// Pedersen commitment to the vote value
    #[serde(rename = "commitment", skip_serializing_if = "Option::is_none")]
    pub commitment: Option<String>,
    /// Blinding factor for the commitment
    #[serde(rename = "blindingFactor", skip_serializing_if = "Option::is_none")]
    pub blinding_factor: Option<String>,
    /// Deterministic nullifier (prevents double-voting)
    #[serde(rename = "nullifier", skip_serializing_if = "Option::is_none")]
    pub nullifier: Option<String>,
    #[serde(rename = "vote", skip_serializing_if = "Option::is_none")]
    pub vote: Option<Vote>,
    #[serde(rename = "proposalId", skip_serializing_if = "Option::is_none")]
    pub proposal_id: Option<String>,
    /// Anonymous voter identifier (stealth address or hash)
    #[serde(rename = "anonymousId", skip_serializing_if = "Option::is_none")]
    pub anonymous_id: Option<String>,
}

impl EncryptBallot200ResponseData {
    pub fn new() -> EncryptBallot200ResponseData {
        EncryptBallot200ResponseData {
            commitment: None,
            blinding_factor: None,
            nullifier: None,
            vote: None,
            proposal_id: None,
            anonymous_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Vote {
    #[serde(rename = "yes")]
    Yes,
    #[serde(rename = "no")]
    No,
    #[serde(rename = "abstain")]
    Abstain,
}

impl Default for Vote {
    fn default() -> Vote {
        Self::Yes
    }
}

