/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmTransferData {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Recipient or token contract address
    #[serde(rename = "to")]
    pub to: String,
    /// Native currency amount (wei)
    #[serde(rename = "value")]
    pub value: String,
    /// Calldata (0x for native, ABI-encoded for ERC20)
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "chainId")]
    pub chain_id: i32,
    #[serde(rename = "tokenContract", skip_serializing_if = "Option::is_none")]
    pub token_contract: Option<String>,
}

impl EvmTransferData {
    pub fn new(r#type: Type, to: String, value: String, data: String, chain_id: i32) -> EvmTransferData {
        EvmTransferData {
            r#type,
            to,
            value,
            data,
            chain_id,
            token_contract: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "evm")]
    Evm,
}

impl Default for Type {
    fn default() -> Type {
        Self::Evm
    }
}

