/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetReady200ResponseDataChecks {
    #[serde(rename = "solana", skip_serializing_if = "Option::is_none")]
    pub solana: Option<bool>,
    #[serde(rename = "shutdown", skip_serializing_if = "Option::is_none")]
    pub shutdown: Option<bool>,
}

impl GetReady200ResponseDataChecks {
    pub fn new() -> GetReady200ResponseDataChecks {
        GetReady200ResponseDataChecks {
            solana: None,
            shutdown: None,
        }
    }
}

