/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateSwapRequest {
    /// Base58-encoded Solana public key
    #[serde(rename = "sender")]
    pub sender: String,
    /// SPL token mint to swap from
    #[serde(rename = "inputMint")]
    pub input_mint: String,
    /// Amount to swap (smallest units)
    #[serde(rename = "inputAmount")]
    pub input_amount: String,
    /// SPL token mint to swap to
    #[serde(rename = "outputMint")]
    pub output_mint: String,
    /// Slippage tolerance in basis points (default 50 = 0.5%)
    #[serde(rename = "slippageBps", skip_serializing_if = "Option::is_none")]
    pub slippage_bps: Option<i32>,
    #[serde(rename = "recipientMetaAddress", skip_serializing_if = "Option::is_none")]
    pub recipient_meta_address: Option<Box<models::PrivateSwapRequestRecipientMetaAddress>>,
}

impl PrivateSwapRequest {
    pub fn new(sender: String, input_mint: String, input_amount: String, output_mint: String) -> PrivateSwapRequest {
        PrivateSwapRequest {
            sender,
            input_mint,
            input_amount,
            output_mint,
            slippage_bps: None,
            recipient_meta_address: None,
        }
    }
}

