/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofsFundingGenerate200ResponseData {
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<Box<models::ProofsFundingGenerate200ResponseDataProof>>,
    #[serde(rename = "publicInputs", skip_serializing_if = "Option::is_none")]
    pub public_inputs: Option<Vec<String>>,
}

impl ProofsFundingGenerate200ResponseData {
    pub fn new() -> ProofsFundingGenerate200ResponseData {
        ProofsFundingGenerate200ResponseData {
            proof: None,
            public_inputs: None,
        }
    }
}

