/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanPaymentsBatch200ResponseDataSummary {
    #[serde(rename = "totalKeyPairs", skip_serializing_if = "Option::is_none")]
    pub total_key_pairs: Option<i32>,
    #[serde(rename = "totalPaymentsFound", skip_serializing_if = "Option::is_none")]
    pub total_payments_found: Option<i32>,
    #[serde(rename = "transactionsScanned", skip_serializing_if = "Option::is_none")]
    pub transactions_scanned: Option<i32>,
}

impl ScanPaymentsBatch200ResponseDataSummary {
    pub fn new() -> ScanPaymentsBatch200ResponseDataSummary {
        ScanPaymentsBatch200ResponseDataSummary {
            total_key_pairs: None,
            total_payments_found: None,
            transactions_scanned: None,
        }
    }
}

