/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanPaymentsBatchRequestKeyPairsInner {
    /// 0x-prefixed 32-byte hex string
    #[serde(rename = "viewingPrivateKey")]
    pub viewing_private_key: String,
    /// 0x-prefixed 32-byte hex string
    #[serde(rename = "spendingPublicKey")]
    pub spending_public_key: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ScanPaymentsBatchRequestKeyPairsInner {
    pub fn new(viewing_private_key: String, spending_public_key: String) -> ScanPaymentsBatchRequestKeyPairsInner {
        ScanPaymentsBatchRequestKeyPairsInner {
            viewing_private_key,
            spending_public_key,
            label: None,
        }
    }
}

