/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SolanaTransferData {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Base64-encoded unsigned transaction
    #[serde(rename = "transaction")]
    pub transaction: String,
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<String>,
}

impl SolanaTransferData {
    pub fn new(r#type: Type, transaction: String) -> SolanaTransferData {
        SolanaTransferData {
            r#type,
            transaction,
            mint: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "solana")]
    Solana,
}

impl Default for Type {
    fn default() -> Type {
        Self::Solana
    }
}

