/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StealthDerive200ResponseData {
    #[serde(rename = "stealthAddress", skip_serializing_if = "Option::is_none")]
    pub stealth_address: Option<Box<models::StealthAddress>>,
    /// 0x-prefixed 32-byte hex string
    #[serde(rename = "sharedSecret", skip_serializing_if = "Option::is_none")]
    pub shared_secret: Option<String>,
}

impl StealthDerive200ResponseData {
    pub fn new() -> StealthDerive200ResponseData {
        StealthDerive200ResponseData {
            stealth_address: None,
            shared_secret: None,
        }
    }
}

