/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StealthDeriveRequest {
    #[serde(rename = "recipientMetaAddress")]
    pub recipient_meta_address: Box<models::StealthMetaAddress>,
}

impl StealthDeriveRequest {
    pub fn new(recipient_meta_address: models::StealthMetaAddress) -> StealthDeriveRequest {
        StealthDeriveRequest {
            recipient_meta_address: Box::new(recipient_meta_address),
        }
    }
}

