/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitArciumComputation200ResponseData {
    #[serde(rename = "computationId", skip_serializing_if = "Option::is_none")]
    pub computation_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "estimatedCompletion", skip_serializing_if = "Option::is_none")]
    pub estimated_completion: Option<i32>,
    #[serde(rename = "circuitId", skip_serializing_if = "Option::is_none")]
    pub circuit_id: Option<String>,
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
    #[serde(rename = "inputCount", skip_serializing_if = "Option::is_none")]
    pub input_count: Option<i32>,
}

impl SubmitArciumComputation200ResponseData {
    pub fn new() -> SubmitArciumComputation200ResponseData {
        SubmitArciumComputation200ResponseData {
            computation_id: None,
            status: None,
            estimated_completion: None,
            circuit_id: None,
            chain: None,
            input_count: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "submitted")]
    Submitted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Submitted
    }
}

