/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitArciumComputationRequest {
    /// Circuit identifier
    #[serde(rename = "circuitId")]
    pub circuit_id: CircuitId,
    /// Encrypted inputs as hex strings
    #[serde(rename = "encryptedInputs")]
    pub encrypted_inputs: Vec<String>,
    /// Target chain
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
    #[serde(rename = "cipher", skip_serializing_if = "Option::is_none")]
    pub cipher: Option<Cipher>,
    #[serde(rename = "viewingKey", skip_serializing_if = "Option::is_none")]
    pub viewing_key: Option<Box<models::SubmitArciumComputationRequestViewingKey>>,
    /// MPC cluster to use
    #[serde(rename = "cluster", skip_serializing_if = "Option::is_none")]
    pub cluster: Option<String>,
    /// Timeout in milliseconds
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
}

impl SubmitArciumComputationRequest {
    pub fn new(circuit_id: CircuitId, encrypted_inputs: Vec<String>) -> SubmitArciumComputationRequest {
        SubmitArciumComputationRequest {
            circuit_id,
            encrypted_inputs,
            chain: None,
            cipher: None,
            viewing_key: None,
            cluster: None,
            timeout: None,
        }
    }
}
/// Circuit identifier
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CircuitId {
    #[serde(rename = "private_transfer")]
    PrivateTransfer,
    #[serde(rename = "check_balance")]
    CheckBalance,
    #[serde(rename = "validate_swap")]
    ValidateSwap,
}

impl Default for CircuitId {
    fn default() -> CircuitId {
        Self::PrivateTransfer
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cipher {
    #[serde(rename = "aes128")]
    Aes128,
    #[serde(rename = "aes192")]
    Aes192,
    #[serde(rename = "aes256")]
    Aes256,
    #[serde(rename = "rescue")]
    Rescue,
}

impl Default for Cipher {
    fn default() -> Cipher {
        Self::Aes128
    }
}

