/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferShieldRequest {
    /// Base58-encoded Solana public key
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "recipientMetaAddress")]
    pub recipient_meta_address: Box<models::StealthMetaAddress>,
    /// Positive integer as string (no leading zeros)
    #[serde(rename = "amount")]
    pub amount: String,
    /// Optional SPL token mint. Omit for native SOL.
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<String>,
}

impl TransferShieldRequest {
    pub fn new(sender: String, recipient_meta_address: models::StealthMetaAddress, amount: String) -> TransferShieldRequest {
        TransferShieldRequest {
            sender,
            recipient_meta_address: Box::new(recipient_meta_address),
            amount,
            mint: None,
        }
    }
}

