/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferPrivate422Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<Success>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::TransferPrivate422ResponseError>>,
}

impl TransferPrivate422Response {
    pub fn new() -> TransferPrivate422Response {
        TransferPrivate422Response {
            success: None,
            error: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Success {
    #[serde(rename = "false")]
    False,
}

impl Default for Success {
    fn default() -> Success {
        Self::False
    }
}

