/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferPrivateRequestRecipientMetaAddress {
    /// 32-byte (ed25519) or 33-byte (secp256k1) hex key
    #[serde(rename = "spendingKey")]
    pub spending_key: String,
    /// 32-byte (ed25519) or 33-byte (secp256k1) hex key
    #[serde(rename = "viewingKey")]
    pub viewing_key: String,
    #[serde(rename = "chain")]
    pub chain: Chain,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl TransferPrivateRequestRecipientMetaAddress {
    pub fn new(spending_key: String, viewing_key: String, chain: Chain) -> TransferPrivateRequestRecipientMetaAddress {
        TransferPrivateRequestRecipientMetaAddress {
            spending_key,
            viewing_key,
            chain,
            label: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Chain {
    #[serde(rename = "solana")]
    Solana,
    #[serde(rename = "near")]
    Near,
    #[serde(rename = "aptos")]
    Aptos,
    #[serde(rename = "sui")]
    Sui,
    #[serde(rename = "ethereum")]
    Ethereum,
    #[serde(rename = "polygon")]
    Polygon,
    #[serde(rename = "arbitrum")]
    Arbitrum,
    #[serde(rename = "optimism")]
    Optimism,
    #[serde(rename = "base")]
    Base,
    #[serde(rename = "bitcoin")]
    Bitcoin,
    #[serde(rename = "zcash")]
    Zcash,
    #[serde(rename = "cosmos")]
    Cosmos,
    #[serde(rename = "osmosis")]
    Osmosis,
    #[serde(rename = "injective")]
    Injective,
    #[serde(rename = "celestia")]
    Celestia,
    #[serde(rename = "sei")]
    Sei,
    #[serde(rename = "dydx")]
    Dydx,
}

impl Default for Chain {
    fn default() -> Chain {
        Self::Solana
    }
}

