/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSessionRequest {
    #[serde(rename = "defaults")]
    pub defaults: Box<models::CreateSessionRequestDefaults>,
}

impl UpdateSessionRequest {
    pub fn new(defaults: models::CreateSessionRequestDefaults) -> UpdateSessionRequest {
        UpdateSessionRequest {
            defaults: Box::new(defaults),
        }
    }
}

