/*
 * Sipher — Privacy-as-a-Skill API
 *
 * REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViewingKeyVerifyHierarchyRequest {
    #[serde(rename = "parentKey")]
    pub parent_key: Box<models::ViewingKey>,
    #[serde(rename = "childKey")]
    pub child_key: Box<models::ViewingKey>,
    #[serde(rename = "childPath")]
    pub child_path: String,
}

impl ViewingKeyVerifyHierarchyRequest {
    pub fn new(parent_key: models::ViewingKey, child_key: models::ViewingKey, child_path: String) -> ViewingKeyVerifyHierarchyRequest {
        ViewingKeyVerifyHierarchyRequest {
            parent_key: Box::new(parent_key),
            child_key: Box::new(child_key),
            child_path,
        }
    }
}

