/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSession201Response,
  CreateSessionRequest,
  DeleteSession200Response,
  GetHealth503Response,
  GetSession200Response,
  UpdateSession200Response,
  UpdateSessionRequest,
} from '../models/index';
import {
    CreateSession201ResponseFromJSON,
    CreateSession201ResponseToJSON,
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    DeleteSession200ResponseFromJSON,
    DeleteSession200ResponseToJSON,
    GetHealth503ResponseFromJSON,
    GetHealth503ResponseToJSON,
    GetSession200ResponseFromJSON,
    GetSession200ResponseToJSON,
    UpdateSession200ResponseFromJSON,
    UpdateSession200ResponseToJSON,
    UpdateSessionRequestFromJSON,
    UpdateSessionRequestToJSON,
} from '../models/index';

export interface CreateSessionOperationRequest {
    createSessionRequest: CreateSessionRequest;
}

export interface DeleteSessionRequest {
    id: string;
}

export interface GetSessionRequest {
    id: string;
}

export interface UpdateSessionOperationRequest {
    id: string;
    updateSessionRequest: UpdateSessionRequest;
}

/**
 * SessionsApi - interface
 * 
 * @export
 * @interface SessionsApiInterface
 */
export interface SessionsApiInterface {
    /**
     * Creates a session that stores default parameters (chain, backend, privacy level, etc.) applied to all subsequent requests via the X-Session-Id header. Requires pro or enterprise tier.
     * @summary Create agent session with default parameters (pro+)
     * @param {CreateSessionRequest} createSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApiInterface
     */
    createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSession201Response>>;

    /**
     * Creates a session that stores default parameters (chain, backend, privacy level, etc.) applied to all subsequent requests via the X-Session-Id header. Requires pro or enterprise tier.
     * Create agent session with default parameters (pro+)
     */
    createSession(createSessionRequest: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSession201Response>;

    /**
     * Ends and deletes the session. The session ID will no longer be valid for subsequent requests.
     * @summary Delete session (pro+)
     * @param {string} id Session ID returned from POST /v1/sessions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApiInterface
     */
    deleteSessionRaw(requestParameters: DeleteSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSession200Response>>;

    /**
     * Ends and deletes the session. The session ID will no longer be valid for subsequent requests.
     * Delete session (pro+)
     */
    deleteSession(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSession200Response>;

    /**
     * Retrieves session details including defaults and expiry. Only the session owner (same API key) can access it.
     * @summary Get session configuration (pro+)
     * @param {string} id Session ID returned from POST /v1/sessions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApiInterface
     */
    getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSession200Response>>;

    /**
     * Retrieves session details including defaults and expiry. Only the session owner (same API key) can access it.
     * Get session configuration (pro+)
     */
    getSession(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSession200Response>;

    /**
     * Merges new defaults into the existing session. Only provided keys are updated; omitted keys remain unchanged.
     * @summary Update session defaults (pro+)
     * @param {string} id Session ID returned from POST /v1/sessions
     * @param {UpdateSessionRequest} updateSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApiInterface
     */
    updateSessionRaw(requestParameters: UpdateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateSession200Response>>;

    /**
     * Merges new defaults into the existing session. Only provided keys are updated; omitted keys remain unchanged.
     * Update session defaults (pro+)
     */
    updateSession(id: string, updateSessionRequest: UpdateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateSession200Response>;

}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI implements SessionsApiInterface {

    /**
     * Creates a session that stores default parameters (chain, backend, privacy level, etc.) applied to all subsequent requests via the X-Session-Id header. Requires pro or enterprise tier.
     * Create agent session with default parameters (pro+)
     */
    async createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSession201Response>> {
        if (requestParameters['createSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSessionRequest',
                'Required parameter "createSessionRequest" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSession201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a session that stores default parameters (chain, backend, privacy level, etc.) applied to all subsequent requests via the X-Session-Id header. Requires pro or enterprise tier.
     * Create agent session with default parameters (pro+)
     */
    async createSession(createSessionRequest: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSession201Response> {
        const response = await this.createSessionRaw({ createSessionRequest: createSessionRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Ends and deletes the session. The session ID will no longer be valid for subsequent requests.
     * Delete session (pro+)
     */
    async deleteSessionRaw(requestParameters: DeleteSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSession200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Ends and deletes the session. The session ID will no longer be valid for subsequent requests.
     * Delete session (pro+)
     */
    async deleteSession(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSession200Response> {
        const response = await this.deleteSessionRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves session details including defaults and expiry. Only the session owner (same API key) can access it.
     * Get session configuration (pro+)
     */
    async getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSession200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves session details including defaults and expiry. Only the session owner (same API key) can access it.
     * Get session configuration (pro+)
     */
    async getSession(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSession200Response> {
        const response = await this.getSessionRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Merges new defaults into the existing session. Only provided keys are updated; omitted keys remain unchanged.
     * Update session defaults (pro+)
     */
    async updateSessionRaw(requestParameters: UpdateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateSession200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSession().'
            );
        }

        if (requestParameters['updateSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSessionRequest',
                'Required parameter "updateSessionRequest" was null or undefined when calling updateSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSessionRequestToJSON(requestParameters['updateSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Merges new defaults into the existing session. Only provided keys are updated; omitted keys remain unchanged.
     * Update session defaults (pro+)
     */
    async updateSession(id: string, updateSessionRequest: UpdateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateSession200Response> {
        const response = await this.updateSessionRaw({ id: id, updateSessionRequest: updateSessionRequest }, initOverrides);
        return await response.value();
    }

}
