/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHealth503Response,
  StealthCheck200Response,
  StealthCheckRequest,
  StealthDerive200Response,
  StealthDeriveRequest,
  StealthGenerate200Response,
  StealthGenerateBatch200Response,
  StealthGenerateBatchRequest,
  StealthGenerateRequest,
} from '../models/index';
import {
    GetHealth503ResponseFromJSON,
    GetHealth503ResponseToJSON,
    StealthCheck200ResponseFromJSON,
    StealthCheck200ResponseToJSON,
    StealthCheckRequestFromJSON,
    StealthCheckRequestToJSON,
    StealthDerive200ResponseFromJSON,
    StealthDerive200ResponseToJSON,
    StealthDeriveRequestFromJSON,
    StealthDeriveRequestToJSON,
    StealthGenerate200ResponseFromJSON,
    StealthGenerate200ResponseToJSON,
    StealthGenerateBatch200ResponseFromJSON,
    StealthGenerateBatch200ResponseToJSON,
    StealthGenerateBatchRequestFromJSON,
    StealthGenerateBatchRequestToJSON,
    StealthGenerateRequestFromJSON,
    StealthGenerateRequestToJSON,
} from '../models/index';

export interface StealthCheckOperationRequest {
    stealthCheckRequest: StealthCheckRequest;
}

export interface StealthDeriveOperationRequest {
    stealthDeriveRequest: StealthDeriveRequest;
}

export interface StealthGenerateOperationRequest {
    stealthGenerateRequest: StealthGenerateRequest;
}

export interface StealthGenerateBatchOperationRequest {
    stealthGenerateBatchRequest: StealthGenerateBatchRequest;
}

/**
 * StealthApi - interface
 * 
 * @export
 * @interface StealthApiInterface
 */
export interface StealthApiInterface {
    /**
     * 
     * @summary Check stealth address ownership
     * @param {StealthCheckRequest} stealthCheckRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StealthApiInterface
     */
    stealthCheckRaw(requestParameters: StealthCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthCheck200Response>>;

    /**
     * Check stealth address ownership
     */
    stealthCheck(stealthCheckRequest: StealthCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthCheck200Response>;

    /**
     * 
     * @summary Derive one-time stealth address
     * @param {StealthDeriveRequest} stealthDeriveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StealthApiInterface
     */
    stealthDeriveRaw(requestParameters: StealthDeriveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthDerive200Response>>;

    /**
     * Derive one-time stealth address
     */
    stealthDerive(stealthDeriveRequest: StealthDeriveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthDerive200Response>;

    /**
     * 
     * @summary Generate stealth meta-address keypair
     * @param {StealthGenerateRequest} stealthGenerateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StealthApiInterface
     */
    stealthGenerateRaw(requestParameters: StealthGenerateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthGenerate200Response>>;

    /**
     * Generate stealth meta-address keypair
     */
    stealthGenerate(stealthGenerateRequest: StealthGenerateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthGenerate200Response>;

    /**
     * Generate multiple stealth meta-address keypairs in a single call. Max 100 per request.
     * @summary Batch generate stealth keypairs
     * @param {StealthGenerateBatchRequest} stealthGenerateBatchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StealthApiInterface
     */
    stealthGenerateBatchRaw(requestParameters: StealthGenerateBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthGenerateBatch200Response>>;

    /**
     * Generate multiple stealth meta-address keypairs in a single call. Max 100 per request.
     * Batch generate stealth keypairs
     */
    stealthGenerateBatch(stealthGenerateBatchRequest: StealthGenerateBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthGenerateBatch200Response>;

}

/**
 * 
 */
export class StealthApi extends runtime.BaseAPI implements StealthApiInterface {

    /**
     * Check stealth address ownership
     */
    async stealthCheckRaw(requestParameters: StealthCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthCheck200Response>> {
        if (requestParameters['stealthCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'stealthCheckRequest',
                'Required parameter "stealthCheckRequest" was null or undefined when calling stealthCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/stealth/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StealthCheckRequestToJSON(requestParameters['stealthCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StealthCheck200ResponseFromJSON(jsonValue));
    }

    /**
     * Check stealth address ownership
     */
    async stealthCheck(stealthCheckRequest: StealthCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthCheck200Response> {
        const response = await this.stealthCheckRaw({ stealthCheckRequest: stealthCheckRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Derive one-time stealth address
     */
    async stealthDeriveRaw(requestParameters: StealthDeriveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthDerive200Response>> {
        if (requestParameters['stealthDeriveRequest'] == null) {
            throw new runtime.RequiredError(
                'stealthDeriveRequest',
                'Required parameter "stealthDeriveRequest" was null or undefined when calling stealthDerive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/stealth/derive`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StealthDeriveRequestToJSON(requestParameters['stealthDeriveRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StealthDerive200ResponseFromJSON(jsonValue));
    }

    /**
     * Derive one-time stealth address
     */
    async stealthDerive(stealthDeriveRequest: StealthDeriveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthDerive200Response> {
        const response = await this.stealthDeriveRaw({ stealthDeriveRequest: stealthDeriveRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Generate stealth meta-address keypair
     */
    async stealthGenerateRaw(requestParameters: StealthGenerateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthGenerate200Response>> {
        if (requestParameters['stealthGenerateRequest'] == null) {
            throw new runtime.RequiredError(
                'stealthGenerateRequest',
                'Required parameter "stealthGenerateRequest" was null or undefined when calling stealthGenerate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/stealth/generate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StealthGenerateRequestToJSON(requestParameters['stealthGenerateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StealthGenerate200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate stealth meta-address keypair
     */
    async stealthGenerate(stealthGenerateRequest: StealthGenerateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthGenerate200Response> {
        const response = await this.stealthGenerateRaw({ stealthGenerateRequest: stealthGenerateRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Generate multiple stealth meta-address keypairs in a single call. Max 100 per request.
     * Batch generate stealth keypairs
     */
    async stealthGenerateBatchRaw(requestParameters: StealthGenerateBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StealthGenerateBatch200Response>> {
        if (requestParameters['stealthGenerateBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'stealthGenerateBatchRequest',
                'Required parameter "stealthGenerateBatchRequest" was null or undefined when calling stealthGenerateBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/stealth/generate/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StealthGenerateBatchRequestToJSON(requestParameters['stealthGenerateBatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StealthGenerateBatch200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate multiple stealth meta-address keypairs in a single call. Max 100 per request.
     * Batch generate stealth keypairs
     */
    async stealthGenerateBatch(stealthGenerateBatchRequest: StealthGenerateBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StealthGenerateBatch200Response> {
        const response = await this.stealthGenerateBatchRaw({ stealthGenerateBatchRequest: stealthGenerateBatchRequest }, initOverrides);
        return await response.value();
    }

}
