/* tslint:disable */
/* eslint-disable */
/**
 * Sipher — Privacy-as-a-Skill API
 * REST API wrapping SIP Protocol\'s privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hello@sip-protocol.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHealth503Response,
  TransferClaim200Response,
  TransferClaimRequest,
  TransferPrivate200Response,
  TransferPrivate422Response,
  TransferPrivateRequest,
  TransferShield200Response,
  TransferShieldRequest,
} from '../models/index';
import {
    GetHealth503ResponseFromJSON,
    GetHealth503ResponseToJSON,
    TransferClaim200ResponseFromJSON,
    TransferClaim200ResponseToJSON,
    TransferClaimRequestFromJSON,
    TransferClaimRequestToJSON,
    TransferPrivate200ResponseFromJSON,
    TransferPrivate200ResponseToJSON,
    TransferPrivate422ResponseFromJSON,
    TransferPrivate422ResponseToJSON,
    TransferPrivateRequestFromJSON,
    TransferPrivateRequestToJSON,
    TransferShield200ResponseFromJSON,
    TransferShield200ResponseToJSON,
    TransferShieldRequestFromJSON,
    TransferShieldRequestToJSON,
} from '../models/index';

export interface TransferClaimOperationRequest {
    transferClaimRequest: TransferClaimRequest;
}

export interface TransferPrivateOperationRequest {
    transferPrivateRequest: TransferPrivateRequest;
}

export interface TransferShieldOperationRequest {
    transferShieldRequest: TransferShieldRequest;
}

/**
 * TransferApi - interface
 * 
 * @export
 * @interface TransferApiInterface
 */
export interface TransferApiInterface {
    /**
     * Derives stealth private key, signs and submits claim transaction on-chain.
     * @summary Claim stealth payment (signed)
     * @param {TransferClaimRequest} transferClaimRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    transferClaimRaw(requestParameters: TransferClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferClaim200Response>>;

    /**
     * Derives stealth private key, signs and submits claim transaction on-chain.
     * Claim stealth payment (signed)
     */
    transferClaim(transferClaimRequest: TransferClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferClaim200Response>;

    /**
     * Builds a private transfer to a stealth address on any supported chain. Returns chain-specific transaction data (Solana unsigned tx, EVM tx descriptor, or NEAR action descriptors). Currently supports: solana, ethereum, polygon, arbitrum, optimism, base, near.
     * @summary Build unified private transfer (chain-agnostic)
     * @param {TransferPrivateRequest} transferPrivateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    transferPrivateRaw(requestParameters: TransferPrivateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferPrivate200Response>>;

    /**
     * Builds a private transfer to a stealth address on any supported chain. Returns chain-specific transaction data (Solana unsigned tx, EVM tx descriptor, or NEAR action descriptors). Currently supports: solana, ethereum, polygon, arbitrum, optimism, base, near.
     * Build unified private transfer (chain-agnostic)
     */
    transferPrivate(transferPrivateRequest: TransferPrivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferPrivate200Response>;

    /**
     * Creates an unsigned Solana transaction sending to a stealth address with Pedersen commitment.
     * @summary Build shielded transfer (unsigned)
     * @param {TransferShieldRequest} transferShieldRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransferApiInterface
     */
    transferShieldRaw(requestParameters: TransferShieldOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferShield200Response>>;

    /**
     * Creates an unsigned Solana transaction sending to a stealth address with Pedersen commitment.
     * Build shielded transfer (unsigned)
     */
    transferShield(transferShieldRequest: TransferShieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferShield200Response>;

}

/**
 * 
 */
export class TransferApi extends runtime.BaseAPI implements TransferApiInterface {

    /**
     * Derives stealth private key, signs and submits claim transaction on-chain.
     * Claim stealth payment (signed)
     */
    async transferClaimRaw(requestParameters: TransferClaimOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferClaim200Response>> {
        if (requestParameters['transferClaimRequest'] == null) {
            throw new runtime.RequiredError(
                'transferClaimRequest',
                'Required parameter "transferClaimRequest" was null or undefined when calling transferClaim().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/transfer/claim`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferClaimRequestToJSON(requestParameters['transferClaimRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferClaim200ResponseFromJSON(jsonValue));
    }

    /**
     * Derives stealth private key, signs and submits claim transaction on-chain.
     * Claim stealth payment (signed)
     */
    async transferClaim(transferClaimRequest: TransferClaimRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferClaim200Response> {
        const response = await this.transferClaimRaw({ transferClaimRequest: transferClaimRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Builds a private transfer to a stealth address on any supported chain. Returns chain-specific transaction data (Solana unsigned tx, EVM tx descriptor, or NEAR action descriptors). Currently supports: solana, ethereum, polygon, arbitrum, optimism, base, near.
     * Build unified private transfer (chain-agnostic)
     */
    async transferPrivateRaw(requestParameters: TransferPrivateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferPrivate200Response>> {
        if (requestParameters['transferPrivateRequest'] == null) {
            throw new runtime.RequiredError(
                'transferPrivateRequest',
                'Required parameter "transferPrivateRequest" was null or undefined when calling transferPrivate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/transfer/private`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferPrivateRequestToJSON(requestParameters['transferPrivateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferPrivate200ResponseFromJSON(jsonValue));
    }

    /**
     * Builds a private transfer to a stealth address on any supported chain. Returns chain-specific transaction data (Solana unsigned tx, EVM tx descriptor, or NEAR action descriptors). Currently supports: solana, ethereum, polygon, arbitrum, optimism, base, near.
     * Build unified private transfer (chain-agnostic)
     */
    async transferPrivate(transferPrivateRequest: TransferPrivateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferPrivate200Response> {
        const response = await this.transferPrivateRaw({ transferPrivateRequest: transferPrivateRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Creates an unsigned Solana transaction sending to a stealth address with Pedersen commitment.
     * Build shielded transfer (unsigned)
     */
    async transferShieldRaw(requestParameters: TransferShieldOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferShield200Response>> {
        if (requestParameters['transferShieldRequest'] == null) {
            throw new runtime.RequiredError(
                'transferShieldRequest',
                'Required parameter "transferShieldRequest" was null or undefined when calling transferShield().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/transfer/shield`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferShieldRequestToJSON(requestParameters['transferShieldRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferShield200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates an unsigned Solana transaction sending to a stealth address with Pedersen commitment.
     * Build shielded transfer (unsigned)
     */
    async transferShield(transferShieldRequest: TransferShieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferShield200Response> {
        const response = await this.transferShieldRaw({ transferShieldRequest: transferShieldRequest }, initOverrides);
        return await response.value();
    }

}
