/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the UpdateSession200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSession200ResponseData{}

// UpdateSession200ResponseData struct for UpdateSession200ResponseData
type UpdateSession200ResponseData struct {
	SessionId *string `json:"sessionId,omitempty"`
	Defaults map[string]interface{} `json:"defaults,omitempty"`
	ExpiresAt *int32 `json:"expiresAt,omitempty"`
	LastAccessedAt *int32 `json:"lastAccessedAt,omitempty"`
}

// NewUpdateSession200ResponseData instantiates a new UpdateSession200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSession200ResponseData() *UpdateSession200ResponseData {
	this := UpdateSession200ResponseData{}
	return &this
}

// NewUpdateSession200ResponseDataWithDefaults instantiates a new UpdateSession200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSession200ResponseDataWithDefaults() *UpdateSession200ResponseData {
	this := UpdateSession200ResponseData{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *UpdateSession200ResponseData) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSession200ResponseData) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *UpdateSession200ResponseData) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *UpdateSession200ResponseData) SetSessionId(v string) {
	o.SessionId = &v
}

// GetDefaults returns the Defaults field value if set, zero value otherwise.
func (o *UpdateSession200ResponseData) GetDefaults() map[string]interface{} {
	if o == nil || IsNil(o.Defaults) {
		var ret map[string]interface{}
		return ret
	}
	return o.Defaults
}

// GetDefaultsOk returns a tuple with the Defaults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSession200ResponseData) GetDefaultsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Defaults) {
		return map[string]interface{}{}, false
	}
	return o.Defaults, true
}

// HasDefaults returns a boolean if a field has been set.
func (o *UpdateSession200ResponseData) HasDefaults() bool {
	if o != nil && !IsNil(o.Defaults) {
		return true
	}

	return false
}

// SetDefaults gets a reference to the given map[string]interface{} and assigns it to the Defaults field.
func (o *UpdateSession200ResponseData) SetDefaults(v map[string]interface{}) {
	o.Defaults = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *UpdateSession200ResponseData) GetExpiresAt() int32 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int32
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSession200ResponseData) GetExpiresAtOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *UpdateSession200ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int32 and assigns it to the ExpiresAt field.
func (o *UpdateSession200ResponseData) SetExpiresAt(v int32) {
	o.ExpiresAt = &v
}

// GetLastAccessedAt returns the LastAccessedAt field value if set, zero value otherwise.
func (o *UpdateSession200ResponseData) GetLastAccessedAt() int32 {
	if o == nil || IsNil(o.LastAccessedAt) {
		var ret int32
		return ret
	}
	return *o.LastAccessedAt
}

// GetLastAccessedAtOk returns a tuple with the LastAccessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSession200ResponseData) GetLastAccessedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.LastAccessedAt) {
		return nil, false
	}
	return o.LastAccessedAt, true
}

// HasLastAccessedAt returns a boolean if a field has been set.
func (o *UpdateSession200ResponseData) HasLastAccessedAt() bool {
	if o != nil && !IsNil(o.LastAccessedAt) {
		return true
	}

	return false
}

// SetLastAccessedAt gets a reference to the given int32 and assigns it to the LastAccessedAt field.
func (o *UpdateSession200ResponseData) SetLastAccessedAt(v int32) {
	o.LastAccessedAt = &v
}

func (o UpdateSession200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSession200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Defaults) {
		toSerialize["defaults"] = o.Defaults
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.LastAccessedAt) {
		toSerialize["lastAccessedAt"] = o.LastAccessedAt
	}
	return toSerialize, nil
}

type NullableUpdateSession200ResponseData struct {
	value *UpdateSession200ResponseData
	isSet bool
}

func (v NullableUpdateSession200ResponseData) Get() *UpdateSession200ResponseData {
	return v.value
}

func (v *NullableUpdateSession200ResponseData) Set(val *UpdateSession200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSession200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSession200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSession200ResponseData(val *UpdateSession200ResponseData) *NullableUpdateSession200ResponseData {
	return &NullableUpdateSession200ResponseData{value: val, isSet: true}
}

func (v NullableUpdateSession200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSession200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


