/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"time"
)

// checks if the GetBillingSubscription200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBillingSubscription200ResponseData{}

// GetBillingSubscription200ResponseData struct for GetBillingSubscription200ResponseData
type GetBillingSubscription200ResponseData struct {
	Id *string `json:"id,omitempty"`
	Plan *string `json:"plan,omitempty"`
	Status *string `json:"status,omitempty"`
	CurrentPeriodStart *time.Time `json:"currentPeriodStart,omitempty"`
	CurrentPeriodEnd *time.Time `json:"currentPeriodEnd,omitempty"`
}

// NewGetBillingSubscription200ResponseData instantiates a new GetBillingSubscription200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBillingSubscription200ResponseData() *GetBillingSubscription200ResponseData {
	this := GetBillingSubscription200ResponseData{}
	return &this
}

// NewGetBillingSubscription200ResponseDataWithDefaults instantiates a new GetBillingSubscription200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBillingSubscription200ResponseDataWithDefaults() *GetBillingSubscription200ResponseData {
	this := GetBillingSubscription200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetBillingSubscription200ResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBillingSubscription200ResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetBillingSubscription200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetBillingSubscription200ResponseData) SetId(v string) {
	o.Id = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *GetBillingSubscription200ResponseData) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBillingSubscription200ResponseData) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *GetBillingSubscription200ResponseData) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *GetBillingSubscription200ResponseData) SetPlan(v string) {
	o.Plan = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetBillingSubscription200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBillingSubscription200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetBillingSubscription200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetBillingSubscription200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetCurrentPeriodStart returns the CurrentPeriodStart field value if set, zero value otherwise.
func (o *GetBillingSubscription200ResponseData) GetCurrentPeriodStart() time.Time {
	if o == nil || IsNil(o.CurrentPeriodStart) {
		var ret time.Time
		return ret
	}
	return *o.CurrentPeriodStart
}

// GetCurrentPeriodStartOk returns a tuple with the CurrentPeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBillingSubscription200ResponseData) GetCurrentPeriodStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CurrentPeriodStart) {
		return nil, false
	}
	return o.CurrentPeriodStart, true
}

// HasCurrentPeriodStart returns a boolean if a field has been set.
func (o *GetBillingSubscription200ResponseData) HasCurrentPeriodStart() bool {
	if o != nil && !IsNil(o.CurrentPeriodStart) {
		return true
	}

	return false
}

// SetCurrentPeriodStart gets a reference to the given time.Time and assigns it to the CurrentPeriodStart field.
func (o *GetBillingSubscription200ResponseData) SetCurrentPeriodStart(v time.Time) {
	o.CurrentPeriodStart = &v
}

// GetCurrentPeriodEnd returns the CurrentPeriodEnd field value if set, zero value otherwise.
func (o *GetBillingSubscription200ResponseData) GetCurrentPeriodEnd() time.Time {
	if o == nil || IsNil(o.CurrentPeriodEnd) {
		var ret time.Time
		return ret
	}
	return *o.CurrentPeriodEnd
}

// GetCurrentPeriodEndOk returns a tuple with the CurrentPeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBillingSubscription200ResponseData) GetCurrentPeriodEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CurrentPeriodEnd) {
		return nil, false
	}
	return o.CurrentPeriodEnd, true
}

// HasCurrentPeriodEnd returns a boolean if a field has been set.
func (o *GetBillingSubscription200ResponseData) HasCurrentPeriodEnd() bool {
	if o != nil && !IsNil(o.CurrentPeriodEnd) {
		return true
	}

	return false
}

// SetCurrentPeriodEnd gets a reference to the given time.Time and assigns it to the CurrentPeriodEnd field.
func (o *GetBillingSubscription200ResponseData) SetCurrentPeriodEnd(v time.Time) {
	o.CurrentPeriodEnd = &v
}

func (o GetBillingSubscription200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBillingSubscription200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CurrentPeriodStart) {
		toSerialize["currentPeriodStart"] = o.CurrentPeriodStart
	}
	if !IsNil(o.CurrentPeriodEnd) {
		toSerialize["currentPeriodEnd"] = o.CurrentPeriodEnd
	}
	return toSerialize, nil
}

type NullableGetBillingSubscription200ResponseData struct {
	value *GetBillingSubscription200ResponseData
	isSet bool
}

func (v NullableGetBillingSubscription200ResponseData) Get() *GetBillingSubscription200ResponseData {
	return v.value
}

func (v *NullableGetBillingSubscription200ResponseData) Set(val *GetBillingSubscription200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBillingSubscription200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBillingSubscription200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBillingSubscription200ResponseData(val *GetBillingSubscription200ResponseData) *NullableGetBillingSubscription200ResponseData {
	return &NullableGetBillingSubscription200ResponseData{value: val, isSet: true}
}

func (v NullableGetBillingSubscription200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBillingSubscription200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


