/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ListAdminTiers200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAdminTiers200ResponseData{}

// ListAdminTiers200ResponseData struct for ListAdminTiers200ResponseData
type ListAdminTiers200ResponseData struct {
	Tiers []ListAdminTiers200ResponseDataTiersInner `json:"tiers,omitempty"`
}

// NewListAdminTiers200ResponseData instantiates a new ListAdminTiers200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAdminTiers200ResponseData() *ListAdminTiers200ResponseData {
	this := ListAdminTiers200ResponseData{}
	return &this
}

// NewListAdminTiers200ResponseDataWithDefaults instantiates a new ListAdminTiers200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAdminTiers200ResponseDataWithDefaults() *ListAdminTiers200ResponseData {
	this := ListAdminTiers200ResponseData{}
	return &this
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *ListAdminTiers200ResponseData) GetTiers() []ListAdminTiers200ResponseDataTiersInner {
	if o == nil || IsNil(o.Tiers) {
		var ret []ListAdminTiers200ResponseDataTiersInner
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAdminTiers200ResponseData) GetTiersOk() ([]ListAdminTiers200ResponseDataTiersInner, bool) {
	if o == nil || IsNil(o.Tiers) {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *ListAdminTiers200ResponseData) HasTiers() bool {
	if o != nil && !IsNil(o.Tiers) {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []ListAdminTiers200ResponseDataTiersInner and assigns it to the Tiers field.
func (o *ListAdminTiers200ResponseData) SetTiers(v []ListAdminTiers200ResponseDataTiersInner) {
	o.Tiers = v
}

func (o ListAdminTiers200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAdminTiers200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tiers) {
		toSerialize["tiers"] = o.Tiers
	}
	return toSerialize, nil
}

type NullableListAdminTiers200ResponseData struct {
	value *ListAdminTiers200ResponseData
	isSet bool
}

func (v NullableListAdminTiers200ResponseData) Get() *ListAdminTiers200ResponseData {
	return v.value
}

func (v *NullableListAdminTiers200ResponseData) Set(val *ListAdminTiers200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListAdminTiers200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListAdminTiers200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAdminTiers200ResponseData(val *ListAdminTiers200ResponseData) *NullableListAdminTiers200ResponseData {
	return &NullableListAdminTiers200ResponseData{value: val, isSet: true}
}

func (v NullableListAdminTiers200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAdminTiers200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


