/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSessionRequest{}

// CreateSessionRequest struct for CreateSessionRequest
type CreateSessionRequest struct {
	Defaults CreateSessionRequestDefaults `json:"defaults"`
	// Session TTL in seconds (default: 3600, max: 86400)
	TtlSeconds *int32 `json:"ttlSeconds,omitempty"`
}

type _CreateSessionRequest CreateSessionRequest

// NewCreateSessionRequest instantiates a new CreateSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSessionRequest(defaults CreateSessionRequestDefaults) *CreateSessionRequest {
	this := CreateSessionRequest{}
	this.Defaults = defaults
	return &this
}

// NewCreateSessionRequestWithDefaults instantiates a new CreateSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSessionRequestWithDefaults() *CreateSessionRequest {
	this := CreateSessionRequest{}
	return &this
}

// GetDefaults returns the Defaults field value
func (o *CreateSessionRequest) GetDefaults() CreateSessionRequestDefaults {
	if o == nil {
		var ret CreateSessionRequestDefaults
		return ret
	}

	return o.Defaults
}

// GetDefaultsOk returns a tuple with the Defaults field value
// and a boolean to check if the value has been set.
func (o *CreateSessionRequest) GetDefaultsOk() (*CreateSessionRequestDefaults, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Defaults, true
}

// SetDefaults sets field value
func (o *CreateSessionRequest) SetDefaults(v CreateSessionRequestDefaults) {
	o.Defaults = v
}

// GetTtlSeconds returns the TtlSeconds field value if set, zero value otherwise.
func (o *CreateSessionRequest) GetTtlSeconds() int32 {
	if o == nil || IsNil(o.TtlSeconds) {
		var ret int32
		return ret
	}
	return *o.TtlSeconds
}

// GetTtlSecondsOk returns a tuple with the TtlSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSessionRequest) GetTtlSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TtlSeconds) {
		return nil, false
	}
	return o.TtlSeconds, true
}

// HasTtlSeconds returns a boolean if a field has been set.
func (o *CreateSessionRequest) HasTtlSeconds() bool {
	if o != nil && !IsNil(o.TtlSeconds) {
		return true
	}

	return false
}

// SetTtlSeconds gets a reference to the given int32 and assigns it to the TtlSeconds field.
func (o *CreateSessionRequest) SetTtlSeconds(v int32) {
	o.TtlSeconds = &v
}

func (o CreateSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["defaults"] = o.Defaults
	if !IsNil(o.TtlSeconds) {
		toSerialize["ttlSeconds"] = o.TtlSeconds
	}
	return toSerialize, nil
}

func (o *CreateSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"defaults",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSessionRequest := _CreateSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSessionRequest)

	if err != nil {
		return err
	}

	*o = CreateSessionRequest(varCreateSessionRequest)

	return err
}

type NullableCreateSessionRequest struct {
	value *CreateSessionRequest
	isSet bool
}

func (v NullableCreateSessionRequest) Get() *CreateSessionRequest {
	return v.value
}

func (v *NullableCreateSessionRequest) Set(val *CreateSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSessionRequest(val *CreateSessionRequest) *NullableCreateSessionRequest {
	return &NullableCreateSessionRequest{value: val, isSet: true}
}

func (v NullableCreateSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


