/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"time"
)

// checks if the GetAdminKey200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdminKey200ResponseData{}

// GetAdminKey200ResponseData struct for GetAdminKey200ResponseData
type GetAdminKey200ResponseData struct {
	Id *string `json:"id,omitempty"`
	// Masked key (first 12 + last 4 chars)
	Key *string `json:"key,omitempty"`
	Tier *string `json:"tier,omitempty"`
	Name *string `json:"name,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
	Limits map[string]interface{} `json:"limits,omitempty"`
	Usage map[string]interface{} `json:"usage,omitempty"`
}

// NewGetAdminKey200ResponseData instantiates a new GetAdminKey200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdminKey200ResponseData() *GetAdminKey200ResponseData {
	this := GetAdminKey200ResponseData{}
	return &this
}

// NewGetAdminKey200ResponseDataWithDefaults instantiates a new GetAdminKey200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdminKey200ResponseDataWithDefaults() *GetAdminKey200ResponseData {
	this := GetAdminKey200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetAdminKey200ResponseData) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GetAdminKey200ResponseData) SetKey(v string) {
	o.Key = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *GetAdminKey200ResponseData) SetTier(v string) {
	o.Tier = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAdminKey200ResponseData) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetAdminKey200ResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *GetAdminKey200ResponseData) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given time.Time and assigns it to the RevokedAt field.
func (o *GetAdminKey200ResponseData) SetRevokedAt(v time.Time) {
	o.RevokedAt = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetLimits() map[string]interface{} {
	if o == nil || IsNil(o.Limits) {
		var ret map[string]interface{}
		return ret
	}
	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetLimitsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Limits) {
		return map[string]interface{}{}, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given map[string]interface{} and assigns it to the Limits field.
func (o *GetAdminKey200ResponseData) SetLimits(v map[string]interface{}) {
	o.Limits = v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *GetAdminKey200ResponseData) GetUsage() map[string]interface{} {
	if o == nil || IsNil(o.Usage) {
		var ret map[string]interface{}
		return ret
	}
	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdminKey200ResponseData) GetUsageOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Usage) {
		return map[string]interface{}{}, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *GetAdminKey200ResponseData) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given map[string]interface{} and assigns it to the Usage field.
func (o *GetAdminKey200ResponseData) SetUsage(v map[string]interface{}) {
	o.Usage = v
}

func (o GetAdminKey200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdminKey200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revokedAt"] = o.RevokedAt
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableGetAdminKey200ResponseData struct {
	value *GetAdminKey200ResponseData
	isSet bool
}

func (v NullableGetAdminKey200ResponseData) Get() *GetAdminKey200ResponseData {
	return v.value
}

func (v *NullableGetAdminKey200ResponseData) Set(val *GetAdminKey200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdminKey200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdminKey200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdminKey200ResponseData(val *GetAdminKey200ResponseData) *NullableGetAdminKey200ResponseData {
	return &NullableGetAdminKey200ResponseData{value: val, isSet: true}
}

func (v NullableGetAdminKey200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdminKey200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


