/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the SubmitJitoBundle200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitJitoBundle200ResponseData{}

// SubmitJitoBundle200ResponseData struct for SubmitJitoBundle200ResponseData
type SubmitJitoBundle200ResponseData struct {
	BundleId *string `json:"bundleId,omitempty" validate:"regexp=^jito_[0-9a-fA-F]{64}$"`
	Status *string `json:"status,omitempty"`
	// Jito tip account address
	TipAccount *string `json:"tipAccount,omitempty"`
	TipLamports *string `json:"tipLamports,omitempty"`
	GasSponsored *bool `json:"gasSponsored,omitempty"`
	Slot *int32 `json:"slot,omitempty"`
	Signature *string `json:"signature,omitempty"`
	EstimatedConfirmation *int32 `json:"estimatedConfirmation,omitempty"`
}

// NewSubmitJitoBundle200ResponseData instantiates a new SubmitJitoBundle200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitJitoBundle200ResponseData() *SubmitJitoBundle200ResponseData {
	this := SubmitJitoBundle200ResponseData{}
	return &this
}

// NewSubmitJitoBundle200ResponseDataWithDefaults instantiates a new SubmitJitoBundle200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitJitoBundle200ResponseDataWithDefaults() *SubmitJitoBundle200ResponseData {
	this := SubmitJitoBundle200ResponseData{}
	return &this
}

// GetBundleId returns the BundleId field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetBundleId() string {
	if o == nil || IsNil(o.BundleId) {
		var ret string
		return ret
	}
	return *o.BundleId
}

// GetBundleIdOk returns a tuple with the BundleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetBundleIdOk() (*string, bool) {
	if o == nil || IsNil(o.BundleId) {
		return nil, false
	}
	return o.BundleId, true
}

// HasBundleId returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasBundleId() bool {
	if o != nil && !IsNil(o.BundleId) {
		return true
	}

	return false
}

// SetBundleId gets a reference to the given string and assigns it to the BundleId field.
func (o *SubmitJitoBundle200ResponseData) SetBundleId(v string) {
	o.BundleId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubmitJitoBundle200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetTipAccount returns the TipAccount field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetTipAccount() string {
	if o == nil || IsNil(o.TipAccount) {
		var ret string
		return ret
	}
	return *o.TipAccount
}

// GetTipAccountOk returns a tuple with the TipAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetTipAccountOk() (*string, bool) {
	if o == nil || IsNil(o.TipAccount) {
		return nil, false
	}
	return o.TipAccount, true
}

// HasTipAccount returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasTipAccount() bool {
	if o != nil && !IsNil(o.TipAccount) {
		return true
	}

	return false
}

// SetTipAccount gets a reference to the given string and assigns it to the TipAccount field.
func (o *SubmitJitoBundle200ResponseData) SetTipAccount(v string) {
	o.TipAccount = &v
}

// GetTipLamports returns the TipLamports field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetTipLamports() string {
	if o == nil || IsNil(o.TipLamports) {
		var ret string
		return ret
	}
	return *o.TipLamports
}

// GetTipLamportsOk returns a tuple with the TipLamports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetTipLamportsOk() (*string, bool) {
	if o == nil || IsNil(o.TipLamports) {
		return nil, false
	}
	return o.TipLamports, true
}

// HasTipLamports returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasTipLamports() bool {
	if o != nil && !IsNil(o.TipLamports) {
		return true
	}

	return false
}

// SetTipLamports gets a reference to the given string and assigns it to the TipLamports field.
func (o *SubmitJitoBundle200ResponseData) SetTipLamports(v string) {
	o.TipLamports = &v
}

// GetGasSponsored returns the GasSponsored field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetGasSponsored() bool {
	if o == nil || IsNil(o.GasSponsored) {
		var ret bool
		return ret
	}
	return *o.GasSponsored
}

// GetGasSponsoredOk returns a tuple with the GasSponsored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetGasSponsoredOk() (*bool, bool) {
	if o == nil || IsNil(o.GasSponsored) {
		return nil, false
	}
	return o.GasSponsored, true
}

// HasGasSponsored returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasGasSponsored() bool {
	if o != nil && !IsNil(o.GasSponsored) {
		return true
	}

	return false
}

// SetGasSponsored gets a reference to the given bool and assigns it to the GasSponsored field.
func (o *SubmitJitoBundle200ResponseData) SetGasSponsored(v bool) {
	o.GasSponsored = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetSlot() int32 {
	if o == nil || IsNil(o.Slot) {
		var ret int32
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetSlotOk() (*int32, bool) {
	if o == nil || IsNil(o.Slot) {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasSlot() bool {
	if o != nil && !IsNil(o.Slot) {
		return true
	}

	return false
}

// SetSlot gets a reference to the given int32 and assigns it to the Slot field.
func (o *SubmitJitoBundle200ResponseData) SetSlot(v int32) {
	o.Slot = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *SubmitJitoBundle200ResponseData) SetSignature(v string) {
	o.Signature = &v
}

// GetEstimatedConfirmation returns the EstimatedConfirmation field value if set, zero value otherwise.
func (o *SubmitJitoBundle200ResponseData) GetEstimatedConfirmation() int32 {
	if o == nil || IsNil(o.EstimatedConfirmation) {
		var ret int32
		return ret
	}
	return *o.EstimatedConfirmation
}

// GetEstimatedConfirmationOk returns a tuple with the EstimatedConfirmation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitJitoBundle200ResponseData) GetEstimatedConfirmationOk() (*int32, bool) {
	if o == nil || IsNil(o.EstimatedConfirmation) {
		return nil, false
	}
	return o.EstimatedConfirmation, true
}

// HasEstimatedConfirmation returns a boolean if a field has been set.
func (o *SubmitJitoBundle200ResponseData) HasEstimatedConfirmation() bool {
	if o != nil && !IsNil(o.EstimatedConfirmation) {
		return true
	}

	return false
}

// SetEstimatedConfirmation gets a reference to the given int32 and assigns it to the EstimatedConfirmation field.
func (o *SubmitJitoBundle200ResponseData) SetEstimatedConfirmation(v int32) {
	o.EstimatedConfirmation = &v
}

func (o SubmitJitoBundle200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitJitoBundle200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BundleId) {
		toSerialize["bundleId"] = o.BundleId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TipAccount) {
		toSerialize["tipAccount"] = o.TipAccount
	}
	if !IsNil(o.TipLamports) {
		toSerialize["tipLamports"] = o.TipLamports
	}
	if !IsNil(o.GasSponsored) {
		toSerialize["gasSponsored"] = o.GasSponsored
	}
	if !IsNil(o.Slot) {
		toSerialize["slot"] = o.Slot
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.EstimatedConfirmation) {
		toSerialize["estimatedConfirmation"] = o.EstimatedConfirmation
	}
	return toSerialize, nil
}

type NullableSubmitJitoBundle200ResponseData struct {
	value *SubmitJitoBundle200ResponseData
	isSet bool
}

func (v NullableSubmitJitoBundle200ResponseData) Get() *SubmitJitoBundle200ResponseData {
	return v.value
}

func (v *NullableSubmitJitoBundle200ResponseData) Set(val *SubmitJitoBundle200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitJitoBundle200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitJitoBundle200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitJitoBundle200ResponseData(val *SubmitJitoBundle200ResponseData) *NullableSubmitJitoBundle200ResponseData {
	return &NullableSubmitJitoBundle200ResponseData{value: val, isSet: true}
}

func (v NullableSubmitJitoBundle200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitJitoBundle200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


