/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
)

// checks if the ListBillingInvoices200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBillingInvoices200ResponseData{}

// ListBillingInvoices200ResponseData struct for ListBillingInvoices200ResponseData
type ListBillingInvoices200ResponseData struct {
	Invoices []interface{} `json:"invoices,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// NewListBillingInvoices200ResponseData instantiates a new ListBillingInvoices200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBillingInvoices200ResponseData() *ListBillingInvoices200ResponseData {
	this := ListBillingInvoices200ResponseData{}
	return &this
}

// NewListBillingInvoices200ResponseDataWithDefaults instantiates a new ListBillingInvoices200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBillingInvoices200ResponseDataWithDefaults() *ListBillingInvoices200ResponseData {
	this := ListBillingInvoices200ResponseData{}
	return &this
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *ListBillingInvoices200ResponseData) GetInvoices() []interface{} {
	if o == nil || IsNil(o.Invoices) {
		var ret []interface{}
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBillingInvoices200ResponseData) GetInvoicesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *ListBillingInvoices200ResponseData) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []interface{} and assigns it to the Invoices field.
func (o *ListBillingInvoices200ResponseData) SetInvoices(v []interface{}) {
	o.Invoices = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListBillingInvoices200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBillingInvoices200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListBillingInvoices200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListBillingInvoices200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ListBillingInvoices200ResponseData) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBillingInvoices200ResponseData) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ListBillingInvoices200ResponseData) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ListBillingInvoices200ResponseData) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ListBillingInvoices200ResponseData) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBillingInvoices200ResponseData) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ListBillingInvoices200ResponseData) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ListBillingInvoices200ResponseData) SetOffset(v int32) {
	o.Offset = &v
}

func (o ListBillingInvoices200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBillingInvoices200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableListBillingInvoices200ResponseData struct {
	value *ListBillingInvoices200ResponseData
	isSet bool
}

func (v NullableListBillingInvoices200ResponseData) Get() *ListBillingInvoices200ResponseData {
	return v.value
}

func (v *NullableListBillingInvoices200ResponseData) Set(val *ListBillingInvoices200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListBillingInvoices200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListBillingInvoices200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBillingInvoices200ResponseData(val *ListBillingInvoices200ResponseData) *NullableListBillingInvoices200ResponseData {
	return &NullableListBillingInvoices200ResponseData{value: val, isSet: true}
}

func (v NullableListBillingInvoices200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBillingInvoices200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


