/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandleBillingWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandleBillingWebhookRequest{}

// HandleBillingWebhookRequest struct for HandleBillingWebhookRequest
type HandleBillingWebhookRequest struct {
	Type string `json:"type"`
	Data map[string]interface{} `json:"data"`
}

type _HandleBillingWebhookRequest HandleBillingWebhookRequest

// NewHandleBillingWebhookRequest instantiates a new HandleBillingWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandleBillingWebhookRequest(type_ string, data map[string]interface{}) *HandleBillingWebhookRequest {
	this := HandleBillingWebhookRequest{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewHandleBillingWebhookRequestWithDefaults instantiates a new HandleBillingWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandleBillingWebhookRequestWithDefaults() *HandleBillingWebhookRequest {
	this := HandleBillingWebhookRequest{}
	return &this
}

// GetType returns the Type field value
func (o *HandleBillingWebhookRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HandleBillingWebhookRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HandleBillingWebhookRequest) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value
func (o *HandleBillingWebhookRequest) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *HandleBillingWebhookRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *HandleBillingWebhookRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o HandleBillingWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandleBillingWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *HandleBillingWebhookRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandleBillingWebhookRequest := _HandleBillingWebhookRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandleBillingWebhookRequest)

	if err != nil {
		return err
	}

	*o = HandleBillingWebhookRequest(varHandleBillingWebhookRequest)

	return err
}

type NullableHandleBillingWebhookRequest struct {
	value *HandleBillingWebhookRequest
	isSet bool
}

func (v NullableHandleBillingWebhookRequest) Get() *HandleBillingWebhookRequest {
	return v.value
}

func (v *NullableHandleBillingWebhookRequest) Set(val *HandleBillingWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandleBillingWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandleBillingWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandleBillingWebhookRequest(val *HandleBillingWebhookRequest) *NullableHandleBillingWebhookRequest {
	return &NullableHandleBillingWebhookRequest{value: val, isSet: true}
}

func (v NullableHandleBillingWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandleBillingWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


