/*
Sipher — Privacy-as-a-Skill API

REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

API version: 0.1.0
Contact: hello@sip-protocol.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sipher

import (
	"encoding/json"
	"time"
)

// checks if the CreateAdminKey201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAdminKey201ResponseData{}

// CreateAdminKey201ResponseData struct for CreateAdminKey201ResponseData
type CreateAdminKey201ResponseData struct {
	Id *string `json:"id,omitempty"`
	// Raw API key — shown only once
	Key *string `json:"key,omitempty"`
	Tier *string `json:"tier,omitempty"`
	Name *string `json:"name,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Limits map[string]interface{} `json:"limits,omitempty"`
	Notice *string `json:"notice,omitempty"`
}

// NewCreateAdminKey201ResponseData instantiates a new CreateAdminKey201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAdminKey201ResponseData() *CreateAdminKey201ResponseData {
	this := CreateAdminKey201ResponseData{}
	return &this
}

// NewCreateAdminKey201ResponseDataWithDefaults instantiates a new CreateAdminKey201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAdminKey201ResponseDataWithDefaults() *CreateAdminKey201ResponseData {
	this := CreateAdminKey201ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateAdminKey201ResponseData) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CreateAdminKey201ResponseData) SetKey(v string) {
	o.Key = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *CreateAdminKey201ResponseData) SetTier(v string) {
	o.Tier = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateAdminKey201ResponseData) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CreateAdminKey201ResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *CreateAdminKey201ResponseData) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetLimits() map[string]interface{} {
	if o == nil || IsNil(o.Limits) {
		var ret map[string]interface{}
		return ret
	}
	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetLimitsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Limits) {
		return map[string]interface{}{}, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given map[string]interface{} and assigns it to the Limits field.
func (o *CreateAdminKey201ResponseData) SetLimits(v map[string]interface{}) {
	o.Limits = v
}

// GetNotice returns the Notice field value if set, zero value otherwise.
func (o *CreateAdminKey201ResponseData) GetNotice() string {
	if o == nil || IsNil(o.Notice) {
		var ret string
		return ret
	}
	return *o.Notice
}

// GetNoticeOk returns a tuple with the Notice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdminKey201ResponseData) GetNoticeOk() (*string, bool) {
	if o == nil || IsNil(o.Notice) {
		return nil, false
	}
	return o.Notice, true
}

// HasNotice returns a boolean if a field has been set.
func (o *CreateAdminKey201ResponseData) HasNotice() bool {
	if o != nil && !IsNil(o.Notice) {
		return true
	}

	return false
}

// SetNotice gets a reference to the given string and assigns it to the Notice field.
func (o *CreateAdminKey201ResponseData) SetNotice(v string) {
	o.Notice = &v
}

func (o CreateAdminKey201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAdminKey201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.Notice) {
		toSerialize["notice"] = o.Notice
	}
	return toSerialize, nil
}

type NullableCreateAdminKey201ResponseData struct {
	value *CreateAdminKey201ResponseData
	isSet bool
}

func (v NullableCreateAdminKey201ResponseData) Get() *CreateAdminKey201ResponseData {
	return v.value
}

func (v *NullableCreateAdminKey201ResponseData) Set(val *CreateAdminKey201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAdminKey201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAdminKey201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAdminKey201ResponseData(val *CreateAdminKey201ResponseData) *NullableCreateAdminKey201ResponseData {
	return &NullableCreateAdminKey201ResponseData{value: val, isSet: true}
}

func (v NullableCreateAdminKey201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAdminKey201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


